/**
 * Shared infrastructure for the inject pipeline.
 *
 * After DX-319 split the pipeline across `sync.ts`, `workspaces.ts`,
 * `per-repo-render.ts`, and `scrubs.ts`, three module-level constants
 * + one helper had to live in every consumer (`projectRoot`, `injectDir`,
 * `log`, `chmodExecutable`). Triplicated `projectRoot` carries non-
 * trivial semantics (the danxbot install root — typo'd `..` count is a
 * silent bug) and the chmod helper is a drift surface; centralizing
 * them here mirrors the existing `src/inject/_shared/hooks/` convention
 * for cross-inject-module shared assets.
 */

import { chmodSync, readFileSync } from "node:fs";
import { dirname, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createLogger } from "../../logger.js";
import { writeIfChanged } from "../../workspace/write-if-changed.js";

/** Danxbot install root — three `..`-pops past `src/inject/_shared/`. */
export const projectRoot: string = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../../..",
);

/** `src/inject/` — one `..`-pop past `src/inject/_shared/`. */
export const injectDir: string = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
);

export const log = createLogger("inject");

export function chmodExecutable(path: string): void {
  try {
    chmodSync(path, 0o755);
  } catch (e) {
    log.warn(`Failed to chmod ${path}:`, e);
  }
}

/**
 * DX-105: canonical write primitive for every inject-pipeline writer in
 * `syncRepoFiles`. Prepends an extension-aware "AUTO-GENERATED by danxbot
 * from <srcRel>" banner so an agent (or human) opening a regenerated file
 * sees a one-line pointer at the source-of-truth and stops editing the
 * derived copy. Pre-DX-105 the inject pipeline had ~9 bare `copyFileSync`
 * / `writeFileSync` callsites with no banner; agents would edit a
 * workspace `.claude/rules/danx-*.md` and have the next poll tick silently
 * overwrite the change.
 *
 * Banner format depends on the destination extension:
 *
 *   `.md`                                 → HTML comment
 *   `.yml` / `.yaml` / `.sh` / `.py` / `.toml` → hash comment
 *   `.json` / `.jsonc`                    → no banner (no comment syntax;
 *                                            pass-through copy)
 *   anything else                         → no banner (pass-through)
 *
 * `.sh` shebang line stays at line 1 — the banner is inserted AFTER the
 * shebang so the shell still recognizes the interpreter. Files without a
 * shebang get the banner at the top like any other hash-comment file.
 *
 * Output is byte-stable across ticks (banner + source content are
 * deterministic per call), so the `writeIfChanged` wrapper short-circuits
 * unchanged writes without bumping inode mtimes.
 *
 * `source` is either `{fileAbs}` (verbatim file copy — read here, NOT in
 * the caller, so the helper owns the read/banner/write contract end-to-
 * end) OR `{content}` (rendered string — used by the three writers that
 * build markdown from `RepoContext` / `config.yml` / `settings.json`).
 * The two-mode API replaces the pre-refactor pattern where callers
 * either inlined their own banner or shipped none at all.
 */
export interface WriteInjectedFileOptions {
  destAbs: string;
  source: { fileAbs: string } | { content: string };
  srcRelToRepoRoot: string;
}

const HASH_BANNER_EXTS = new Set([".yml", ".yaml", ".sh", ".py", ".toml"]);
const SKIP_BANNER_EXTS = new Set([".json", ".jsonc"]);

function readSource(source: WriteInjectedFileOptions["source"]): string {
  if ("fileAbs" in source) return readFileSync(source.fileAbs, "utf-8");
  return source.content;
}

function buildBanner(ext: string, srcRel: string): string | null {
  if (ext === ".md") {
    return `<!-- AUTO-GENERATED by danxbot from ${srcRel}. Do NOT edit — overwritten on next poll. Edit the source. -->\n\n`;
  }
  if (HASH_BANNER_EXTS.has(ext)) {
    return `# AUTO-GENERATED by danxbot from ${srcRel}. Do NOT edit — overwritten on next poll. Edit the source.\n\n`;
  }
  return null;
}

function applyBanner(content: string, banner: string, ext: string): string {
  // `.sh` shebang preservation: banner goes AFTER the shebang line so the
  // kernel still recognizes the interpreter. The shebang convention
  // applies to `.sh` specifically — other hash-comment formats (.py, .toml,
  // .yml) may also legitimately carry a shebang, but the inject pipeline
  // does not write executable scripts of those types today; if a future
  // writer does, broaden this check.
  if (ext === ".sh" && content.startsWith("#!")) {
    const newlineIdx = content.indexOf("\n");
    if (newlineIdx === -1) return `${content}\n${banner}`;
    return `${content.slice(0, newlineIdx + 1)}${banner}${content.slice(newlineIdx + 1)}`;
  }
  return `${banner}${content}`;
}

export function writeInjectedFile(opts: WriteInjectedFileOptions): boolean {
  const { destAbs, source, srcRelToRepoRoot } = opts;
  const ext = extname(destAbs).toLowerCase();
  const rawContent = readSource(source);
  if (SKIP_BANNER_EXTS.has(ext)) {
    return writeIfChanged(destAbs, rawContent);
  }
  const banner = buildBanner(ext, srcRelToRepoRoot);
  if (banner === null) {
    return writeIfChanged(destAbs, rawContent);
  }
  return writeIfChanged(destAbs, applyBanner(rawContent, banner, ext));
}
