/**
 * DX-105: tests for the inject-pipeline write primitive
 * (`writeInjectedFile`).
 *
 * Coverage targets every AC item that constrains banner shape, the
 * shebang preservation, the `.json` pass-through, idempotence across
 * repeated calls, and the source-file-unchanged invariant the inject
 * pipeline depends on (the source is the editable canonical copy; a
 * writer that overwrites its own source on a re-tick is a bug).
 */

import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { writeInjectedFile } from "./inject-utils.js";

let tmpRoot: string;
let srcDir: string;
let destDir: string;

beforeEach(() => {
  tmpRoot = mkdtempSync(resolve(tmpdir(), "write-injected-file-test-"));
  srcDir = resolve(tmpRoot, "src");
  destDir = resolve(tmpRoot, "dest");
  mkdirSync(srcDir, { recursive: true });
  mkdirSync(destDir, { recursive: true });
});

afterEach(() => {
  rmSync(tmpRoot, { recursive: true, force: true });
});

describe("writeInjectedFile — extension-aware banner", () => {
  it("prepends an HTML-comment banner naming the source path for .md files", () => {
    const src = resolve(srcDir, "rule.md");
    const dest = resolve(destDir, "danx-rule.md");
    writeFileSync(src, "# Title\n\nBody.\n");
    writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/rule.md",
    });
    const out = readFileSync(dest, "utf-8");
    expect(out.startsWith("<!-- AUTO-GENERATED by danxbot from ")).toBe(true);
    expect(out).toContain(".danxbot/config/rule.md");
    expect(out).toContain("Do NOT edit");
    expect(out).toContain("# Title\n\nBody.\n");
  });

  it.each(["yml", "yaml", "sh", "py", "toml"])(
    "prepends a hash-comment banner for .%s files",
    (ext) => {
      const src = resolve(srcDir, `payload.${ext}`);
      const dest = resolve(destDir, `payload.${ext}`);
      writeFileSync(src, "body line one\n");
      writeInjectedFile({
        destAbs: dest,
        source: { fileAbs: src },
        srcRelToRepoRoot: `.danxbot/config/payload.${ext}`,
      });
      const out = readFileSync(dest, "utf-8");
      expect(out.startsWith("# AUTO-GENERATED by danxbot from ")).toBe(true);
      expect(out).toContain(`.danxbot/config/payload.${ext}`);
      expect(out).toContain("body line one");
    },
  );

  it("preserves .sh shebang on line 1 and inserts banner after it", () => {
    const src = resolve(srcDir, "tool.sh");
    const dest = resolve(destDir, "tool.sh");
    writeFileSync(src, "#!/usr/bin/env bash\necho hi\n");
    writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/tools/tool.sh",
    });
    const out = readFileSync(dest, "utf-8");
    const lines = out.split("\n");
    expect(lines[0]).toBe("#!/usr/bin/env bash");
    expect(lines[1].startsWith("# AUTO-GENERATED by danxbot from ")).toBe(true);
    expect(out).toContain("echo hi");
  });

  it("inserts banner at the top when .sh has no shebang", () => {
    const src = resolve(srcDir, "no-shebang.sh");
    const dest = resolve(destDir, "no-shebang.sh");
    writeFileSync(src, "echo no-shebang\n");
    writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/tools/no-shebang.sh",
    });
    const out = readFileSync(dest, "utf-8");
    expect(out.startsWith("# AUTO-GENERATED by danxbot from ")).toBe(true);
    expect(out).toContain("echo no-shebang");
  });

  it.each(["json", "jsonc"])(
    "passes through .%s files verbatim (no banner, no comment syntax)",
    (ext) => {
      const src = resolve(srcDir, `cfg.${ext}`);
      const dest = resolve(destDir, `cfg.${ext}`);
      const payload = '{"mcpServers": {}}\n';
      writeFileSync(src, payload);
      writeInjectedFile({
        destAbs: dest,
        source: { fileAbs: src },
        srcRelToRepoRoot: `.danxbot/config/cfg.${ext}`,
      });
      const out = readFileSync(dest, "utf-8");
      expect(out).toBe(payload);
    },
  );

  it("accepts rendered content directly via {content}", () => {
    const dest = resolve(destDir, "rendered.md");
    writeInjectedFile({
      destAbs: dest,
      source: { content: "# Rendered\n\nFrom data.\n" },
      srcRelToRepoRoot: ".danxbot/config/config.yml",
    });
    const out = readFileSync(dest, "utf-8");
    expect(out.startsWith("<!-- AUTO-GENERATED by danxbot from ")).toBe(true);
    expect(out).toContain(".danxbot/config/config.yml");
    expect(out).toContain("# Rendered\n\nFrom data.\n");
  });
});

describe("writeInjectedFile — idempotence", () => {
  it("never double-prepends across repeated calls on the same source", () => {
    const src = resolve(srcDir, "rule.md");
    const dest = resolve(destDir, "danx-rule.md");
    writeFileSync(src, "# Title\n");
    writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/rule.md",
    });
    const firstOut = readFileSync(dest, "utf-8");
    // Second tick — same source, same args.
    writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/rule.md",
    });
    const secondOut = readFileSync(dest, "utf-8");
    expect(secondOut).toBe(firstOut);
    // Banner must appear exactly once.
    expect(secondOut.match(/AUTO-GENERATED by danxbot/g)?.length).toBe(1);
  });

  it("short-circuits the disk write on a no-op (writeIfChanged)", () => {
    const src = resolve(srcDir, "rule.md");
    const dest = resolve(destDir, "danx-rule.md");
    writeFileSync(src, "# Title\n");
    const changed1 = writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/rule.md",
    });
    const changed2 = writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/rule.md",
    });
    expect(changed1).toBe(true);
    expect(changed2).toBe(false);
  });

  it("leaves the source file's content untouched after sync", () => {
    const src = resolve(srcDir, "rule.md");
    const dest = resolve(destDir, "danx-rule.md");
    const original = "# Title\n\nOriginal body.\n";
    writeFileSync(src, original);
    writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/rule.md",
    });
    expect(readFileSync(src, "utf-8")).toBe(original);
  });

  it("re-renders when the source path changes (banner reflects new srcRel)", () => {
    const src = resolve(srcDir, "rule.md");
    const dest = resolve(destDir, "danx-rule.md");
    writeFileSync(src, "# Title\n");
    const changed1 = writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/old-name.md",
    });
    const changed2 = writeInjectedFile({
      destAbs: dest,
      source: { fileAbs: src },
      srcRelToRepoRoot: ".danxbot/config/different-renamed-source.md",
    });
    const out = readFileSync(dest, "utf-8");
    expect(out).toContain(".danxbot/config/different-renamed-source.md");
    expect(out).not.toContain("old-name.md");
    expect(changed1).toBe(true);
    expect(changed2).toBe(true);
  });
});
