#!/usr/bin/env bash
set -euo pipefail

echo "=== Danxbot Setup ==="
echo ""

# Check Node.js >= 20
if ! command -v node &>/dev/null; then
  echo "ERROR: Node.js is not installed."
  echo "Install Node.js 20+ from https://nodejs.org/ or via nvm:"
  echo "  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash"
  echo "  nvm install 20"
  exit 1
fi

NODE_MAJOR=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_MAJOR" -lt 20 ]; then
  echo "ERROR: Node.js 20+ is required (found $(node -v))."
  echo "Upgrade via nvm: nvm install 20"
  exit 1
fi
echo "Node.js $(node -v) OK"

# Check Claude Code CLI
if ! command -v claude &>/dev/null; then
  echo "Claude Code CLI not found — installing..."
  npm i -g @anthropic-ai/claude-code
fi
echo "Claude Code CLI OK"

# Install dependencies (both root and dashboard)
echo "Installing dependencies..."
npm install
cd dashboard && npm install && cd ..

# Build dashboard so the volume mount has dist/ on the host
echo "Building dashboard..."
cd dashboard && npm run build && cd ..

# Hand off to Claude's interactive setup skill
echo ""
echo "Launching interactive setup..."
claude '/setup' --dangerously-skip-permissions

# Trello cjAyJpgr AC6 — pre-create per-repo claude-projects/ dirs at
# install time so the worker compose's static `../../claude-projects`
# bind has a host source owned by UID 1000 (the worker container's
# `danxbot` user). Without this, Docker auto-creates the bind source
# as root-owned on first `compose up` and the in-container user can't
# write JSONL — silent failure mode that surfaces as empty dashboard
# timelines. The Makefile launch-* targets also mkdir as a belt-and-
# suspenders, but install-time creation closes the gap on a fresh
# clone before any launch happens. Idempotent.
#
# `.env` is sourced as shell — trusted-input only (the file is
# generated by the /setup skill above; users who hand-edit it are
# accepting that values run as bash).
if [ -f .env ]; then
  set -a; . ./.env; set +a
fi
# Connected-repo names come from deploy/targets/<DANXBOT_TARGET>.yml
# (default `local`) via the `list-target-repos` helper — same source as
# the Makefile + the runtime, so install + launch + dispatch never
# desync. Pre-Phase-B this iterated `$REPOS` from `.env`.
NAMES="$(DANXBOT_TARGET="${DANXBOT_TARGET:-local}" npx tsx src/cli/list-target-repos.ts 2>/dev/null || true)"
if [ -n "$NAMES" ]; then
  echo ""
  echo "Pre-creating per-repo claude-projects/ dirs..."
  chown_failed=0
  for name in $NAMES; do
    mkdir -p "repos/${name}/claude-projects"
    # chown 1000:1000 — matches the Dockerfile's `useradd -m danxbot`
    # first-non-system uid. Try unprivileged first (works when host
    # UID == 1000), fall back to sudo when it doesn't, fail-soft so
    # install completes even if chown is rejected (the dir still
    # exists and the operator can chown manually). The `WARN:`
    # uppercase prefix matches the `ERROR:` convention above so the
    # message is grep-visible in install output, and the
    # `chown_failed` flag drives a final summary line so install
    # exit 0 doesn't bury the partial-failure signal.
    chown 1000:1000 "repos/${name}/claude-projects" 2>/dev/null || \
      sudo chown 1000:1000 "repos/${name}/claude-projects" 2>/dev/null || {
        echo "WARN: could not chown repos/${name}/claude-projects to 1000:1000 — chown manually before launching the worker"
        chown_failed=1
      }
  done
  if [ "$chown_failed" = "1" ]; then
    echo ""
    echo "WARN: one or more claude-projects dirs were not chowned to 1000:1000."
    echo "      The worker container's danxbot user (UID 1000) may fail to write JSONL."
    echo "      Run: sudo chown 1000:1000 repos/*/claude-projects"
  fi
fi

# Run the poller's inject pipeline once for every connected repo so
# `<repo>/.danxbot/workspaces/trello-worker/.claude/skills/` (and
# rules/tools/workspaces) is populated before the workers boot. Without
# this step, the symlinks created below would dangle until the
# corresponding worker had ticked at least once. Idempotent — the
# poller runs the same `syncRepoFiles` on every tick.
if [ -n "$NAMES" ]; then
  echo ""
  echo "Pre-populating per-repo inject pipeline..."
  npx tsx scripts/sync-repos.ts
fi

# Wire /danx-* skills as symlinks at repo-root .claude/skills/ so the
# developer's interactive `claude` (run from any of these repos) can
# invoke /danx-next, /danx-start, /danx-ideate, /danx-triage. Source
# of truth is danxbot's inject pipeline at
# src/poller/inject/workspaces/trello-worker/.claude/skills/.
#
# - For danxbot itself: symlink → ../../src/poller/inject/.../skills/<n>.
# - For each connected repo in the active target: symlink →
#   ../../.danxbot/workspaces/trello-worker/.claude/skills/<n>. Targets
#   exist because the inject step above ran first.
#
# Idempotent: `ln -sfn` overwrites stale symlinks without prompting.
# Note: `ln -sfn` does NOT replace pre-existing real directories at
# the link path — those have to be removed manually before re-running
# this section. (Only an issue for repos with a stale danx-* dir from
# a prior copy-based install.) Gitignored on both sides via
# `.claude/skills/danx-*` patterns; this script is the only writer.
DANX_SKILLS=(danx-ideate danx-next danx-start danx-triage)

echo ""
echo "Wiring /danx-* skill symlinks..."

# danxbot itself
mkdir -p .claude/skills
for s in "${DANX_SKILLS[@]}"; do
  ln -sfn "../../src/poller/inject/workspaces/trello-worker/.claude/skills/$s" ".claude/skills/$s"
done
echo "  danxbot: ${DANX_SKILLS[*]}"

# Connected repos (loaded from deploy/targets/<DANXBOT_TARGET>.yml above)
if [ -n "$NAMES" ]; then
  for name in $NAMES; do
    if [ ! -d "repos/${name}" ]; then
      echo "  WARN: repos/${name} not present — skipping skill symlinks"
      continue
    fi
    repo_skills_dir="repos/${name}/.claude/skills"
    mkdir -p "$repo_skills_dir"
    for s in "${DANX_SKILLS[@]}"; do
      ln -sfn "../../.danxbot/workspaces/trello-worker/.claude/skills/$s" "$repo_skills_dir/$s"
    done
    echo "  ${name}: ${DANX_SKILLS[*]}"
  done
fi

# Provision / refresh the dashboard root user when DANX_DASHBOARD_ROOT_USER
# is set + the dashboard container is already running. Idempotent — a no-op
# when the password already matches. Skipped silently when infra isn't up
# (operator runs `make launch-infra && make ensure-root-user LOCALHOST=1`
# afterwards). The CLI itself also no-ops when the env var is unset.
if [ -n "${DANX_DASHBOARD_ROOT_USER:-}" ]; then
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -q '^danxbot-dashboard-1$'; then
    echo ""
    echo "Ensuring dashboard root user..."
    make ensure-root-user LOCALHOST=1 || echo "  WARN: ensure-root-user failed — run manually after fixing"
  else
    echo ""
    echo "NOTE: DANX_DASHBOARD_ROOT_USER is set but the dashboard container is"
    echo "      not running. After 'make launch-infra', run:"
    echo "        make ensure-root-user LOCALHOST=1"
  fi
fi
