/**
 * Inject pipeline — per-repo render layer.
 *
 * Split out of `src/inject/sync.ts` in DX-319. For each plural
 * workspace, writes the per-repo rendered files
 * (`danx-repo-config.md`, `danx-repo-overview.md`,
 * `danx-repo-workflow.md`, `danx-tools.md`,
 * `danx-issue-prefix.md`) plus tool scripts into its `.claude/`.
 * Rendered fresh from `RepoContext` every tick so cwd-relative skill
 * references resolve locally.
 *
 * Also carries the small set of repo→danxbot-install copies that pull
 * connected-repo config (compose override, docs, features.md) into the
 * danxbot install tree.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { resolve } from "node:path";
import { renderRepoConfigMarkdown } from "../poller/repo-config-rule.js";
import type { RepoContext } from "../types.js";
import { chmodExecutable, projectRoot } from "./_shared/inject-utils.js";

/**
 * The `.claude/` subtree the inject pipeline writes per-repo files
 * into. Every dispatched agent cwds into one of the plural workspaces
 * at `<repo>/.danxbot/workspaces/<name>/` (agent-isolation +
 * workspace-dispatch epics, Trello `7ha2CSpc`/`jAdeJgi5`), so that's
 * where per-repo rendered rules + tools must land — duplicated into
 * each workspace dir so cwd-relative skill references like
 * `.claude/rules/danx-repo-config.md` resolve LOCALLY without claude
 * having to walk ancestor `.claude/` dirs (which would land on the
 * developer's repo-root `.claude/`, an isolation contract violation
 * that produced the Phase 6 stale-board-IDs incident).
 *
 * The repo-root `.claude/` is strictly developer-owned. Danxbot neither
 * reads nor writes there; `scrubRepoRootDanxArtifacts` actively removes
 * any leftover `danx-*` files at repo-root on every tick.
 */
interface InjectTarget {
  rulesDir: string;
  skillsDir: string;
  toolsDir: string;
}

function buildInjectTarget(workspaceRoot: string): InjectTarget {
  return {
    rulesDir: resolve(workspaceRoot, ".claude/rules"),
    skillsDir: resolve(workspaceRoot, ".claude/skills"),
    toolsDir: resolve(workspaceRoot, ".claude/tools"),
  };
}

/**
 * Names of every `danx-*` rule that `renderPerRepoFilesIntoWorkspaces`
 * writes into a workspace's `.claude/rules/` every tick. Imported by
 * `./workspaces.ts` for the prune allowlist so the prune cannot drift
 * out of sync with the render. Adding a new rendered rule without
 * updating this set would cause the prune to silently delete it on the
 * next tick.
 *
 * Skills directory has no per-repo renders today; if that changes, add
 * a sibling set + thread it through the prune.
 */
export const PER_REPO_RENDER_RULE_NAMES: ReadonlySet<string> = new Set([
  "danx-repo-config.md",
  "danx-repo-overview.md",
  "danx-repo-workflow.md",
  "danx-tools.md",
  "danx-issue-prefix.md",
]);

/** Step 1: render danx-repo-config.md from config.yml to the workspace. */
function writeRepoConfigRule(
  cfg: Record<string, string>,
  target: InjectTarget,
): void {
  writeFileSync(
    resolve(target.rulesDir, "danx-repo-config.md"),
    renderRepoConfigMarkdown(cfg),
  );
}

/** Step 2: overview.md + workflow.md -> danx-repo-{overview,workflow}.md. */
function copyRepoConfigDocs(
  danxbotConfigDir: string,
  target: InjectTarget,
): void {
  const mappings: ReadonlyArray<readonly [string, string]> = [
    ["overview.md", "danx-repo-overview.md"],
    ["workflow.md", "danx-repo-workflow.md"],
  ];
  for (const [src, dest] of mappings) {
    const srcPath = resolve(danxbotConfigDir, src);
    if (!existsSync(srcPath)) continue;
    const header = `<!-- AUTO-GENERATED by danxbot from .danxbot/config/${src} — do not edit -->\n\n`;
    writeFileSync(
      resolve(target.rulesDir, dest),
      header + readFileSync(srcPath, "utf-8"),
    );
  }
}

/**
 * Step 2b: render `danx-issue-prefix.md` from `RepoContext.issuePrefix`.
 *
 * Carries the live per-repo issue prefix (e.g. `DX`, `SG`, `FD`) so
 * workspace skills can reference the actual literal when prose
 * convention `<PREFIX>-N` is insufficient (e.g. examples that need a
 * concrete id, scripts that templated the prefix). Phase 4 of DX-99 —
 * the source-of-truth lookup point for the live value at agent-dispatch
 * time. The prose layer (skills + rules) generally uses `<PREFIX>-N`
 * as a placeholder; this file is the escape hatch for the rare case
 * the literal is needed.
 */
function writeIssuePrefixRule(
  issuePrefix: string,
  target: InjectTarget,
): void {
  const body =
    `<!-- AUTO-GENERATED by danxbot — do not edit. Source: <repo>/.danxbot/config/config.yml#issue_prefix -->\n` +
    `\n` +
    `# Issue ID Prefix\n` +
    `\n` +
    `This repo's issue id prefix is **\`${issuePrefix}\`**.\n` +
    `\n` +
    `Every issue id in this repo has the shape \`${issuePrefix}-<N>\` (e.g. \`${issuePrefix}-1\`, \`${issuePrefix}-42\`). When skill prose says \`<PREFIX>-N\`, substitute \`${issuePrefix}\`. When you need a literal example id in a comment or commit message, use a real \`${issuePrefix}-N\` from this repo.\n`;
  writeFileSync(resolve(target.rulesDir, "danx-issue-prefix.md"), body);
}

/** Step 3: repo-specific tools.md -> danx-tools.md. */
function copyRepoToolsDoc(
  danxbotConfigDir: string,
  target: InjectTarget,
): void {
  const src = resolve(danxbotConfigDir, "tools.md");
  if (!existsSync(src)) return;
  copyFileSync(src, resolve(target.rulesDir, "danx-tools.md"));
}

/** Step 4: repo-specific tool scripts -> .claude/tools/ (executable). */
function copyRepoToolScripts(
  danxbotConfigDir: string,
  target: InjectTarget,
): void {
  const src = resolve(danxbotConfigDir, "tools");
  if (!existsSync(src)) return;
  for (const file of readdirSync(src)) {
    const dest = resolve(target.toolsDir, file);
    copyFileSync(resolve(src, file), dest);
    chmodExecutable(dest);
  }
}

/**
 * For each plural workspace under `<repo>/.danxbot/workspaces/`, render
 * the per-repo files into its `.claude/`. The static mirror created
 * the workspace dirs in stage 1; this stage just adds the per-repo
 * data layer on top. Workspaces from the static inject tree that have
 * never received a tick yet still get the per-repo files written —
 * `injectDanxWorkspaces` ran first, so the dirs exist.
 *
 * Workspaces are discovered from the on-disk `<repo>/.danxbot/workspaces/`
 * directory, not from `inject/workspaces/`. This way an operator-authored
 * workspace tracked in the connected repo's git (the
 * `gpt-manager-authored schema-builder/` precedent that produced the
 * never-prune contract) also gets the per-repo files — the inject
 * pipeline doesn't gate on whether danxbot ships the workspace itself.
 */
export function renderPerRepoFilesIntoWorkspaces(
  repo: RepoContext,
  danxbotConfigDir: string,
  cfg: Record<string, string>,
  workspacesDir: string,
): void {
  if (!existsSync(workspacesDir)) return;
  const names = readdirSync(workspacesDir).filter((entry) => {
    try {
      return statSync(resolve(workspacesDir, entry)).isDirectory();
    } catch {
      return false;
    }
  });

  for (const name of names) {
    const workspaceRoot = resolve(workspacesDir, name);
    const target = buildInjectTarget(workspaceRoot);
    mkdirSync(target.rulesDir, { recursive: true });
    mkdirSync(target.toolsDir, { recursive: true });

    writeRepoConfigRule(cfg, target);
    copyRepoConfigDocs(danxbotConfigDir, target);
    writeIssuePrefixRule(repo.issuePrefix, target);
    copyRepoToolsDoc(danxbotConfigDir, target);
    copyRepoToolScripts(danxbotConfigDir, target);
  }
}

/** Step 7: optional compose override -> repo-overrides/<name>-compose.yml. */
export function copyComposeOverride(
  danxbotConfigDir: string,
  overridesDir: string,
  cfgName: string,
): void {
  const src = resolve(danxbotConfigDir, "compose.yml");
  if (!existsSync(src)) return;
  mkdirSync(overridesDir, { recursive: true });
  copyFileSync(src, resolve(overridesDir, `${cfgName}-compose.yml`));
}

/** Step 8: repo-side docs/{domains,schema}/* -> danxbot docs dir. */
export function copyRepoDocs(danxbotConfigDir: string): void {
  const repoDocsDir = resolve(danxbotConfigDir, "docs");
  if (!existsSync(repoDocsDir)) return;
  const docsDir = resolve(projectRoot, "docs");
  for (const subdir of ["domains", "schema"]) {
    const srcDir = resolve(repoDocsDir, subdir);
    if (!existsSync(srcDir)) continue;
    const destDir = resolve(docsDir, subdir);
    mkdirSync(destDir, { recursive: true });
    for (const file of readdirSync(srcDir)) {
      copyFileSync(resolve(srcDir, file), resolve(destDir, file));
    }
  }
}

/** Step 9: features.md is copied ONCE and left alone so ideator edits persist. */
export function copyFeaturesOnce(danxbotConfigDir: string): void {
  const danxbotDir = resolve(danxbotConfigDir, "..");
  const src = resolve(danxbotDir, "features.md");
  const dest = resolve(projectRoot, "docs", "features.md");
  if (!existsSync(src) || existsSync(dest)) return;
  mkdirSync(resolve(projectRoot, "docs"), { recursive: true });
  copyFileSync(src, dest);
}
