/**
 * Generate `docker-compose.override.yml` for LOCAL DEV ONLY.
 *
 * The dashboard container needs RW access to each connected repo's
 * `.danxbot/` dir so operator toggles on the Agents tab can write
 * `settings.json`. Prod covers this with a single `/danxbot/repos:` parent
 * mount because prod owns that directory's contents. Dev's `./repos/<name>`
 * entries are symlinks into `/home/<user>/web/*`, so a parent-dir mount
 * would either be read-only (breaks toggles) or leak the host path into
 * the container. Per-repo RW binds through each symlink land on the real
 * target without either tradeoff.
 *
 * Compose auto-merges `docker-compose.override.yml` when `docker compose`
 * is invoked WITHOUT `-f`. Prod's `docker compose -f docker-compose.prod.yml`
 * (and the worker compose invocations) all pass `-f` explicitly, which
 * suppresses auto-merge — the override is dashboard-dev-only by mechanism.
 * Any new dev workflow that uses `-f docker-compose.yml` alone would also
 * suppress the merge and regress EROFS.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseReposEnv } from "../repos-env.js";

export const OVERRIDE_FILENAME = "docker-compose.override.yml";
const CONTAINER_REPOS_BASE = "/danxbot/app/repos";

export function buildOverride(repoNames: string[]): string {
  const header = [
    "# Auto-generated by `make generate-dev-override` — do not edit.",
    "# Regenerated from the REPOS env var on every `make launch-infra`.",
    "# See src/cli/dev-compose-override.ts for rationale.",
    "",
  ];

  if (repoNames.length === 0) {
    return [...header, "services: {}", ""].join("\n");
  }

  const binds = repoNames.map(
    (name) => `      - ./repos/${name}:${CONTAINER_REPOS_BASE}/${name}`,
  );

  return [
    ...header,
    "services:",
    "  dashboard:",
    "    volumes:",
    ...binds,
    "",
  ].join("\n");
}

export function writeOverrideFile(
  repoNames: string[],
  projectRoot: string,
): string {
  const path = resolve(projectRoot, OVERRIDE_FILENAME);
  writeFileSync(path, buildOverride(repoNames), "utf-8");
  return path;
}

async function main(): Promise<void> {
  const reposEnv = process.env["REPOS"] ?? "";
  const names = parseReposEnv(reposEnv).map((r) => r.name);
  const path = writeOverrideFile(names, process.cwd());
  const summary =
    names.length === 0
      ? "(no repos configured)"
      : names.map((n) => `./repos/${n}`).join(", ");
  console.log(`Wrote ${path} — ${summary}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
