/**
 * Generate `docker-compose.override.yml` for LOCAL DEV ONLY.
 *
 * The dashboard container needs RW access to each connected repo's
 * `.danxbot/` dir so operator toggles on the Agents tab can write
 * `settings.json`. Prod covers this with a single `/danxbot/repos:` parent
 * mount because prod owns that directory's contents. Dev's `./repos/<name>`
 * entries are symlinks into `/home/<user>/web/*`, so we need a per-repo
 * RW bind for each one — a parent-dir mount would either be read-only
 * (breaks toggles) or leak the host path into the container.
 *
 * ## The WSL2 symlink trap
 *
 * Binding a symlink source directly (`./repos/<name>` where `<name>` is a
 * symlink to a real host dir) does NOT reliably dereference on WSL2 + Docker
 * Desktop: the container ends up with a container-local phantom directory
 * at the mount destination, totally disconnected from the host target. All
 * writes go to the phantom, which is invisible to anything outside that
 * container. Reads return stale / empty content. Observed in the self-
 * hosted case where `repos/danxbot` symlinks back to the repo root.
 *
 * Fix: emit `${DANXBOT_REPO_ROOT_<NAME>:-./repos/<name>}` as the bind
 * source. `make launch-infra` computes `realpath ./repos/<name>` for each
 * entry in `REPOS` and exports the matching env var before invoking
 * `docker compose up`, so the compose-parse pass substitutes in an
 * absolute host path that Docker binds cleanly. This is the exact same
 * mechanism `<repo>/.danxbot/config/compose.yml` uses for the worker
 * containers (`${DANXBOT_REPO_ROOT:-../..}`, set by `make launch-worker`) —
 * just per-repo instead of one-at-a-time.
 *
 * The `./repos/<name>` fallback preserves `docker compose up` against an
 * unset var (defense in depth for direct `docker compose` invocations
 * that bypass the Make target).
 *
 * Compose auto-merges `docker-compose.override.yml` when `docker compose`
 * is invoked WITHOUT `-f`. Prod's `docker compose -f docker-compose.prod.yml`
 * (and the worker compose invocations) all pass `-f` explicitly, which
 * suppresses auto-merge — the override is dashboard-dev-only by mechanism.
 * Any new dev workflow that uses `-f docker-compose.yml` alone would also
 * suppress the merge and regress EROFS.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseReposEnv } from "../repos-env.js";

export const OVERRIDE_FILENAME = "docker-compose.override.yml";
const CONTAINER_REPOS_BASE = "/danxbot/app/repos";
const CONTAINER_CLAUDE_PROJECTS_BASE = "/danxbot/app/claude-projects";

/**
 * Map a repo name to the env var that `make launch-infra` exports with
 * the realpath'd absolute host path. Uppercase + hyphens → underscores
 * so the result is a valid shell identifier (e.g. `gpt-manager` →
 * `DANXBOT_REPO_ROOT_GPT_MANAGER`). The exact same mapping lives in
 * the Makefile's `launch-infra` recipe (`tr 'a-z-' 'A-Z_'`) — the two
 * must stay in lockstep or compose's `${VAR}` interpolation will fall
 * through to the `./repos/<name>` fallback (phantom-directory regression).
 *
 * Throws on any repo name that would produce an invalid shell
 * identifier (anything outside `[a-z0-9-]`). Compose's env-var
 * interpolation silently drops invalid vars and falls through to the
 * fallback — exactly the regression this whole file exists to prevent.
 * Fail loud at codegen instead.
 *
 * Intentional non-overlap with `launch-worker`'s bare `DANXBOT_REPO_ROOT`
 * (set by `make launch-worker REPO=<name>`): the suffixed form here is
 * always `DANXBOT_REPO_ROOT_<NAME>` (name uppercased, never empty), so
 * the two namespaces cannot collide. A hypothetical repo named `""`
 * would throw here before reaching any export.
 */
const SHELL_IDENT_RE = /^[A-Z_][A-Z0-9_]*$/;

export function repoRootVarName(name: string): string {
  const suffix = name.toUpperCase().replace(/-/g, "_");
  const result = `DANXBOT_REPO_ROOT_${suffix}`;
  if (!SHELL_IDENT_RE.test(result)) {
    throw new Error(
      `Repo name "${name}" produces an invalid shell identifier ` +
        `"${result}". Compose's \${VAR} interpolation would silently ` +
        `fall through to the ./repos/<name> fallback (the symlink trap ` +
        `this whole file exists to dodge). Allowed chars in repo name: ` +
        `lowercase letters, digits, and hyphen.`,
    );
  }
  return result;
}

export function buildOverride(repoNames: string[]): string {
  const header = [
    "# Auto-generated by `make generate-dev-override` — do not edit.",
    "# Regenerated from the REPOS env var on every `make launch-infra`.",
    "# See src/cli/dev-compose-override.ts for rationale.",
    "",
  ];

  if (repoNames.length === 0) {
    return [...header, "services: {}", ""].join("\n");
  }

  // RW bind per repo: dashboard needs write access to each repo's .danxbot/
  // so that Agents tab toggles can write settings.json. Bind source is
  // env-var-indirected — see the module docstring for the WSL2 symlink
  // trap this dodges.
  const repoBinds = repoNames.map((name) => {
    const v = repoRootVarName(name);
    return `      - \${${v}:-./repos/${name}}:${CONTAINER_REPOS_BASE}/${name}`;
  });

  // RO bind per repo: mount each repo's claude-projects dir so the dashboard
  // can read JSONL session logs written by that repo's worker container.
  // The path-resolver in src/dashboard/jsonl-path-resolver.ts translates the
  // worker-internal path (/home/danxbot/.claude/projects/...) to this mount.
  // Uses the same env var as the RW bind — the sub-path `/claude-projects`
  // is appended AFTER substitution, so this resolves to
  // `<absolute-repo-root>/claude-projects` at compose-parse time.
  const projectsBinds = repoNames.map((name) => {
    const v = repoRootVarName(name);
    return `      - \${${v}:-./repos/${name}}/claude-projects:${CONTAINER_CLAUDE_PROJECTS_BASE}/${name}:ro`;
  });

  return [
    ...header,
    "services:",
    "  dashboard:",
    "    volumes:",
    ...repoBinds,
    ...projectsBinds,
    "",
  ].join("\n");
}

export function writeOverrideFile(
  repoNames: string[],
  projectRoot: string,
): string {
  const path = resolve(projectRoot, OVERRIDE_FILENAME);
  writeFileSync(path, buildOverride(repoNames), "utf-8");
  return path;
}

async function main(): Promise<void> {
  const reposEnv = process.env["REPOS"] ?? "";
  const names = parseReposEnv(reposEnv).map((r) => r.name);
  const path = writeOverrideFile(names, process.cwd());
  const summary =
    names.length === 0
      ? "(no repos configured)"
      : names.map((n) => `./repos/${n}`).join(", ");
  console.log(`Wrote ${path} — ${summary}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
