/**
 * Danxbot workspace generator — builds `<repo>/.danxbot/workspace/`, the
 * isolated directory every danxbot-dispatched claude agent will eventually
 * use as its cwd (Phase 3 of the agent-isolation epic; see the Trello card
 * `7ha2CSpc` for the full contract).
 *
 * The workspace layout:
 *
 *   <repo>/.danxbot/workspace/
 *     .gitignore                        — everything-but-this-file
 *     CLAUDE.md                         — entry doc for dispatched agents
 *     .claude/
 *       settings.json                   — { env: { DANXBOT_WORKER_PORT } }
 *       rules/                          — danx-* rule docs (poller fills)
 *       skills/                         — danx-* skills (poller fills)
 *       agents/                         — reserved for future subagent defs
 *       tools/                          — danx-* tools (poller fills)
 *
 * Phase 1 scope: create the skeleton directories and write the two files the
 * generator owns (CLAUDE.md, settings.json, .gitignore). The poller's
 * existing `syncRepoFiles()` still populates rules/skills/tools in the
 * target repo's root `.claude/` — Phase 3 switches spawn cwd to the
 * workspace, and Phase 5 cleans up the repo-root writes. This generator
 * being idempotent is load-bearing: both the worker boot and every poller
 * tick call it, and both must converge on the same on-disk shape without
 * clobbering operator-maintained state.
 *
 * What this file intentionally does NOT do:
 *   - Copy rule/skill/tool content. That's the poller's inject pipeline
 *     (`src/poller/inject/` + `syncRepoFiles`). A duplicate copy here
 *     would be a DRY violation and drift between the two.
 *   - Touch `<repo>/.claude/`. The developer's interactive `claude` at
 *     the repo root is use case #1 and its config must stay independent.
 */

import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { getReposBase } from "../poller/constants.js";
import type { RepoContext } from "../types.js";

/**
 * Subdirectory under `<repo>/.danxbot/` that holds the isolated workspace.
 * Exported so callers (poller, worker boot, tests) can compose paths
 * without duplicating the literal.
 */
export const WORKSPACE_SUBDIR = "workspace";

/**
 * Resolve the workspace root for a connected repo. This is the ONE place
 * the `<repo>/.danxbot/workspace/` literal lives — every caller that
 * needs the dispatched-agent cwd goes through here.
 *
 * ## Load-bearing invariant
 *
 * Both overloads MUST resolve to the same absolute path for a given repo.
 * When the input is a `RepoContext`, the result is `repo.localPath +
 * .danxbot/workspace`. When the input is a bare `repoName`, the result
 * is `getReposBase() + repoName + .danxbot/workspace`. Because
 * `loadRepoContext` constructs `repo.localPath === join(getReposBase(),
 * repo.name)` (see `src/config.ts:11` + `src/repo-context.ts:153`), the
 * two forms converge by construction. The parity test in
 * `src/workspace/generate.test.ts` guards this.
 *
 * If that parity ever breaks, three load-bearing consumers diverge:
 *   1. `src/agent/launcher.ts` — spawn cwd of every dispatched claude
 *   2. `src/worker/dispatch.ts` — resume-session directory lookup
 *   3. `src/dashboard/jsonl-path-resolver.ts#encodeRepoCwd` — the
 *      docker-runtime fallback that encodes this path as a dir name
 *      by replacing `/` with `-`
 *
 * The launcher + resume paths call `workspacePath(repoName)` because
 * they only have a string. The poller's `syncRepoFiles` calls
 * `workspacePath(repo)` because it has a loaded `RepoContext`. One
 * helper, two entry shapes, same output.
 *
 * ## Host-mode note
 *
 * `getReposBase()` checks `DANXBOT_REPOS_BASE` first and falls back to
 * `<projectRoot>/repos`. The host-mode worker sets the env var to the
 * real checkout parent, so the string-form helper still produces the
 * correct on-disk path. If `getReposBase()` ever disagrees with how
 * `loadRepoContext` sets `repo.localPath` on a given runtime, this
 * helper becomes wrong for the string form only — a bug the parity
 * test catches at startup.
 */
export function workspacePath(repo: RepoContext): string;
export function workspacePath(repoName: string): string;
export function workspacePath(input: RepoContext | string): string {
  const base =
    typeof input === "string" ? resolve(getReposBase(), input) : input.localPath;
  return resolve(base, ".danxbot", WORKSPACE_SUBDIR);
}

/**
 * Minimal `.gitignore` written at the workspace root. The workspace is
 * fully generated from `.danxbot/config/` + `.danxbot/.env` + the inject
 * pipeline; nothing in it should ever be committed. A leading `*` followed
 * by `!.gitignore` ensures the ignore file itself stays tracked if the
 * parent ever forgets to exclude the whole workspace.
 */
const WORKSPACE_GITIGNORE = `# Generated by danxbot — do not edit.
# The workspace is fully rebuilt from .danxbot/config/ + inject/ at
# every worker boot and every poller tick. Never commit its contents.
*
!.gitignore
`;

/**
 * Minimal project CLAUDE.md for dispatched agents. Points at the rule
 * files the poller's inject pipeline drops alongside — Claude Code
 * auto-loads those when `settingSources: ["project"]` (the default
 * for `--dangerously-skip-permissions`). Keep this intentionally short:
 * any guidance belongs in the injected rule docs, not here, so it stays
 * in sync with the authored rule library under `src/poller/inject/rules/`.
 */
/**
 * Stub `.mcp.json`. Dispatched agents always run with `--strict-mcp-config`
 * + a per-dispatch `--mcp-config`, so project-scope MCP is ignored by
 * design. This file exists purely so the workspace looks like a valid
 * claude project directory — AC #1 requires `.mcp.json` to be present,
 * and a future interactive `cd workspace && claude` diagnostic session
 * sees a well-formed (if empty) MCP config.
 */
const WORKSPACE_MCP_JSON =
  JSON.stringify({ mcpServers: {} }, null, 2) + "\n";

const WORKSPACE_CLAUDE_MD = `# Danxbot Workspace

This directory is a generated, isolated project root for every agent
dispatched by danxbot. It is NOT a normal repo checkout — it contains only
the config, rules, skills, and tools the dispatched agent needs, generated
from \`.danxbot/config/\` and \`.danxbot/.env\` in the connected repo.

## Key Files

- \`.claude/rules/\` — per-repo workflow rules and danxbot-authored rules
- \`.claude/skills/\` — danx-* skills (e.g. \`danx-next\`, \`danx-triage\`)
- \`.claude/tools/\` — danx-* helper scripts
- \`.claude/settings.json\` — worker port (read by helper scripts)
- \`.mcp.json\` — stub MCP config (empty; dispatched agents pass their own via \`--mcp-config --strict-mcp-config\`)

## Do Not Edit

Every file under this directory is overwritten on worker boot and on
every poller tick. Authoritative sources:

- Rule files: \`src/poller/inject/rules/*.md\` in the danxbot repo
- Skills: \`src/poller/inject/skills/**\`
- Tools: \`src/poller/inject/tools/**\`
- Repo-specific content: \`<repo>/.danxbot/config/\`
`;

/**
 * Write a file only if its content differs from what's already on disk.
 * Returns `true` when a write actually happened. Used so worker-boot and
 * poller-tick calls stay idempotent on unchanged config without bumping
 * inode timestamps on every invocation (downstream watchers care).
 */
function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path)) {
    const current = readFileSync(path, "utf-8");
    if (current === content) return false;
  }
  writeFileSync(path, content);
  return true;
}

/**
 * Build the settings.json contents. Includes only the env block that the
 * injected helper scripts rely on — `DANXBOT_WORKER_PORT` for the MCP
 * callback URL. The port itself comes from `repo.workerPort`, which
 * `src/repo-context.ts#readWorkerPort` resolved from `<repo>/.danxbot/.env`
 * (local dev) or `process.env.DANXBOT_WORKER_PORT` (production compose).
 * Keeping the schema narrow and explicit means any drift is visible in
 * diff review rather than silently accumulating.
 */
function buildSettingsJson(repo: RepoContext): string {
  return (
    JSON.stringify(
      {
        env: {
          DANXBOT_WORKER_PORT: String(repo.workerPort),
        },
      },
      null,
      2,
    ) + "\n"
  );
}

export interface GenerateWorkspaceResult {
  /** Absolute path to `<repo>/.danxbot/workspace/`. */
  path: string;
  /** Files that were created or modified on this call. Relative to `path`. */
  changedFiles: string[];
}

/**
 * Ensure the workspace skeleton exists and owner-owned files (CLAUDE.md,
 * settings.json, .gitignore) are up to date. Safe to call repeatedly; no-op
 * when everything is already current.
 *
 * The returned `changedFiles` list is informational only — callers that
 * want to know whether they triggered a real on-disk change (e.g. for
 * logging) can check `changedFiles.length > 0`.
 */
export function generateWorkspace(
  repo: RepoContext,
): GenerateWorkspaceResult {
  const root = workspacePath(repo);
  const claudeDir = resolve(root, ".claude");

  for (const dir of [
    root,
    claudeDir,
    resolve(claudeDir, "rules"),
    resolve(claudeDir, "skills"),
    resolve(claudeDir, "agents"),
    resolve(claudeDir, "tools"),
  ]) {
    mkdirSync(dir, { recursive: true });
  }

  const changedFiles: string[] = [];

  if (writeIfChanged(resolve(root, ".gitignore"), WORKSPACE_GITIGNORE)) {
    changedFiles.push(".gitignore");
  }
  if (writeIfChanged(resolve(root, "CLAUDE.md"), WORKSPACE_CLAUDE_MD)) {
    changedFiles.push("CLAUDE.md");
  }
  if (writeIfChanged(resolve(root, ".mcp.json"), WORKSPACE_MCP_JSON)) {
    changedFiles.push(".mcp.json");
  }
  if (
    writeIfChanged(
      resolve(claudeDir, "settings.json"),
      buildSettingsJson(repo),
    )
  ) {
    changedFiles.push(".claude/settings.json");
  }

  return { path: root, changedFiles };
}
