import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import {
  PRUNE_COMMAND,
  pruneStaleDockerImages,
  renderProdCompose,
  uploadAndRestartInfra,
} from "./compose-infra.js";
import type { RemoteHost } from "./remote.js";

describe("renderProdCompose", () => {
  it("substitutes ECR image and dashboard port", () => {
    const out = renderProdCompose(
      "123.dkr.ecr.us-east-1.amazonaws.com/danxbot-production:latest",
      5555,
      ["danxbot", "gpt-manager"],
    );
    expect(out).toContain(
      "image: 123.dkr.ecr.us-east-1.amazonaws.com/danxbot-production:latest",
    );
    expect(out).toMatch(/"5555:5555"/);
    expect(out).toMatch(/localhost:5555\/health/);
    expect(out).not.toContain("${ECR_IMAGE}");
    expect(out).not.toContain("${DASHBOARD_PORT}");
  });

  it("preserves ${DANXBOT_DB_*} vars (those are resolved by compose at runtime from /danxbot/.env)", () => {
    const out = renderProdCompose("any-image", 5555, ["danxbot"]);
    expect(out).toContain("${DANXBOT_DB_PASSWORD}");
    expect(out).toContain("${DANXBOT_DB_USER}");
  });

  it("substitutes dashboard port on both the host-port mapping and the healthcheck URL", () => {
    const out = renderProdCompose("img", 9000, ["danxbot"]);
    expect(out).toContain('"9000:9000"');
    expect(out).toContain("localhost:9000/health");
  });

  it("mounts each repo's OWN /danxbot/repos/<name>/claude-projects/ at the namespaced dashboard path so jsonl-path-resolver finds per-repo JSONL (Trello cjAyJpgr)", () => {
    // Pre-cjAyJpgr: dashboard mounted ONE shared `/danxbot/claude-projects`
    // source under both `danxbot` and `gpt-manager` namespaces. The fix
    // gives each repo its own source dir matching the dev override layout
    // generated by `src/cli/dev-compose-override.ts` so dev/prod paths
    // are identical and a non-danxbot dispatch's timeline renders.
    const out = renderProdCompose("img", 5555, ["danxbot", "gpt-manager"]);
    expect(out).toContain(
      "/danxbot/repos/danxbot/claude-projects:/danxbot/app/claude-projects/danxbot:ro",
    );
    expect(out).toContain(
      "/danxbot/repos/gpt-manager/claude-projects:/danxbot/app/claude-projects/gpt-manager:ro",
    );
    // Regression guard — the shared-source mount lines must NOT come back.
    // Literal lines (not just substrings, since per-repo paths CONTAIN the
    // legacy substring as part of `/danxbot/repos/<name>/claude-projects:...`).
    expect(out).not.toMatch(/^\s*-\s*\/danxbot\/claude-projects:/m);
  });

  it("emits a mount per repo in the deploy config — three repos produces three lines", () => {
    const out = renderProdCompose("img", 5555, ["a", "b", "c"]);
    expect(out).toContain("/danxbot/repos/a/claude-projects:/danxbot/app/claude-projects/a:ro");
    expect(out).toContain("/danxbot/repos/b/claude-projects:/danxbot/app/claude-projects/b:ro");
    expect(out).toContain("/danxbot/repos/c/claude-projects:/danxbot/app/claude-projects/c:ro");
  });

  it("emits no claude-projects mounts when the repo list is empty (a degenerate but valid deploy config)", () => {
    const out = renderProdCompose("img", 5555, []);
    expect(out).not.toContain(":/danxbot/app/claude-projects/");
    // The remaining template still substitutes correctly.
    expect(out).toContain("image: img");
  });

  it("leaves no unsubstituted ${CLAUDE_PROJECTS_MOUNTS} token in the rendered output — guards against template/code rename drift", () => {
    // The placeholder name in the template (`${CLAUDE_PROJECTS_MOUNTS}`) and
    // the key passed to `applyTemplateVars` must match exactly. A rename in
    // one file but not the other would be silent: `applyTemplateVars` leaves
    // unmatched `${...}` tokens in place, compose's parser would then fail
    // at `docker compose up` time with an opaque "invalid mount source"
    // error. This test catches the drift at unit-test time.
    const out = renderProdCompose("img", 5555, ["danxbot"]);
    expect(out).not.toMatch(/\$\{CLAUDE_PROJECTS_MOUNTS\}/);
  });

  it("emits each claude-projects mount line with exactly 6-space indent + leading hyphen — yaml structure must be preserved by the substitution", () => {
    // The placeholder in the template lives at column 0 (it's its own line);
    // the rendered lines are responsible for their own indent. If a future
    // refactor changed the join shape (e.g. added a `\n      - ` prefix and
    // a `\n` suffix), the first or last line could lose indent and produce
    // invalid yaml. Pin the shape with a per-line regex check.
    const out = renderProdCompose("img", 5555, ["danxbot", "gpt-manager"]);
    const mountLines = out
      .split("\n")
      .filter((l) => l.includes(":/danxbot/app/claude-projects/"));
    expect(mountLines.length).toBe(2);
    for (const line of mountLines) {
      expect(line).toMatch(/^      - \//);
    }
  });
});

describe("uploadAndRestartInfra", () => {
  // Stub RemoteHost — `uploadAndRestartInfra` orchestrates SCP + several
  // sshRun/sshRunStreaming calls. We capture them in arrays and assert
  // the regression-guard properties without touching SSH or the network.
  function captureRemote(): {
    calls: string[];
    streamingCalls: string[];
    scpUploads: Array<[string, string]>;
    remote: RemoteHost;
  } {
    const calls: string[] = [];
    const streamingCalls: string[] = [];
    const scpUploads: Array<[string, string]> = [];
    const remote = {
      sshRun: (cmd: string) => calls.push(cmd),
      sshRunStreaming: (cmd: string) => streamingCalls.push(cmd),
      scpUpload: (src: string, dst: string) => scpUploads.push([src, dst]),
    } as unknown as RemoteHost;
    return { calls, streamingCalls, scpUploads, remote };
  }

  it("does NOT mkdir the legacy shared /danxbot/claude-projects dir (Trello cjAyJpgr deleted that step)", () => {
    // Pre-cjAyJpgr the function ran `sudo mkdir -p /danxbot/claude-projects
    // && sudo chown 1000:1000 /danxbot/claude-projects`. Per-repo dirs are
    // now created by `launchWorkers` instead. A regression here would
    // recreate the shared dir AND silently keep working in dev (no harm)
    // but mismatch the new dashboard mounts in prod (those source from
    // `/danxbot/repos/<name>/claude-projects/`).
    const { calls, remote } = captureRemote();
    uploadAndRestartInfra(remote, "img", 5555, "us-east-1", ["danxbot"]);
    for (const c of calls) {
      expect(c).not.toMatch(/mkdir -p \/danxbot\/claude-projects(\s|$)/);
    }
  });

  it("threads repoNames into the rendered compose so the per-repo dashboard mounts appear in the uploaded yaml", () => {
    // Spy on writeFileSync via a helper that captures the rendered yaml.
    // We can't easily intercept the temp-file write without mocking node:fs,
    // so we verify the END-TO-END outcome by reading the file the function
    // actually wrote. uploadAndRestartInfra writes to `mkdtempSync` under
    // os.tmpdir() — capture by patching scpUpload to read its src arg.
    let uploadedYaml = "";
    const remote = {
      sshRun: () => {},
      sshRunStreaming: () => {},
      scpUpload: (src: string, dst: string) => {
        // uploadAndRestartInfra now ships two artifacts: the rendered
        // compose file and the playwright-screenshot/ tarball. Filter on
        // the destination so this test stays focused on the compose yaml.
        if (dst.endsWith("docker-compose.prod.yml")) {
          uploadedYaml = readFileSync(src, "utf-8");
        }
      },
    } as unknown as RemoteHost;

    uploadAndRestartInfra(remote, "img", 5555, "us-east-1", [
      "danxbot",
      "gpt-manager",
    ]);

    expect(uploadedYaml).toContain(
      "/danxbot/repos/danxbot/claude-projects:/danxbot/app/claude-projects/danxbot:ro",
    );
    expect(uploadedYaml).toContain(
      "/danxbot/repos/gpt-manager/claude-projects:/danxbot/app/claude-projects/gpt-manager:ro",
    );
    // Negative guard — the legacy shared-source line must not be in the rendered yaml.
    expect(uploadedYaml).not.toMatch(/^\s*-\s*\/danxbot\/claude-projects:/m);
  });

  it("ships the playwright-screenshot/ build context so prod compose's `build: ./playwright-screenshot` resolves on the instance (Trello 4u13Qe8r)", () => {
    // The prod compose template uses `build: ./playwright-screenshot`
    // identically to local. Without the source on the instance, docker
    // compose up fails with "no such file or directory" instead of building.
    // The legacy shape (`image: mcr.microsoft.com/playwright:...`) ran a
    // base image with no HTTP server inside — restart loop forever.
    const { scpUploads, calls, remote } = captureRemote();
    uploadAndRestartInfra(remote, "img", 5555, "us-east-1", ["danxbot"]);

    // tarball uploaded to /tmp on the instance
    const tarUploads = scpUploads.filter(([, dst]) =>
      dst.endsWith("playwright-screenshot.tar"),
    );
    expect(tarUploads.length).toBe(1);

    // extracted under /danxbot with ubuntu ownership; remote tar removed
    const extractCmd = calls.find((c) => c.includes("tar -xf"));
    expect(extractCmd).toBeDefined();
    expect(extractCmd).toContain(
      "/tmp/playwright-screenshot.tar -C /danxbot",
    );
    expect(extractCmd).toContain(
      "sudo rm -rf /danxbot/playwright-screenshot",
    );
    expect(extractCmd).toContain(
      "sudo chown -R ubuntu:ubuntu /danxbot/playwright-screenshot",
    );
  });

  it("invokes `docker compose up -d --build` so the playwright service is rebuilt from source on every deploy", () => {
    // Without --build, compose reuses whatever cached image is tagged for
    // the service — which on the FIRST deploy after this card lands does
    // not exist (the legacy base-image entry was deleted). --build also
    // ensures a server.ts edit on the next deploy actually ships.
    const { streamingCalls, remote } = captureRemote();
    uploadAndRestartInfra(remote, "img", 5555, "us-east-1", ["danxbot"]);

    const upCmd = streamingCalls.find((c) => c.includes("compose"));
    expect(upCmd).toContain("--build");
    expect(upCmd).toContain("up -d");
  });
});

describe("prod compose template", () => {
  it("uses `build: ./playwright-screenshot` matching local docker-compose.yml — Trello 4u13Qe8r", () => {
    // Local builds from source; prod must too. The legacy shape
    // (`image: mcr.microsoft.com/playwright:v1.40.0-jammy`) shipped a base
    // image with no HTTP server and stuck in a restart loop on prod.
    // Locking the build-context shape prevents a future agent from
    // "simplifying" back to an off-the-shelf image without checking that
    // the image actually serves /screenshot, /html, /health.
    const out = renderProdCompose("img", 5555, ["danxbot"]);
    expect(out).toContain("build: ./playwright-screenshot");
    expect(out).not.toMatch(/image:\s+mcr\.microsoft\.com\/playwright/);
  });
});

describe("pruneStaleDockerImages", () => {
  it("PRUNE_COMMAND prunes ONLY unreferenced images — never volumes, networks, or system-wide", () => {
    // The deploy host runs the dashboard, MySQL, two workers, and Playwright
    // — `system prune` could remove the danxbot-net network mid-deploy and
    // disconnect everything. `--volumes` could nuke the MySQL data volume.
    // Lock the safety surface so a future "be more aggressive" tweak can't
    // silently destroy state without flipping these assertions red.
    expect(PRUNE_COMMAND).toBe("docker image prune -af");
    expect(PRUNE_COMMAND).not.toContain("system");
    expect(PRUNE_COMMAND).not.toContain("--volumes");
    expect(PRUNE_COMMAND).not.toContain("volume");
    expect(PRUNE_COMMAND).not.toContain("network");
  });

  it("issues exactly one sshRunStreaming call with PRUNE_COMMAND", () => {
    // Stub RemoteHost: only the methods pruneStaleDockerImages touches need
    // to be real. Keeps the test hermetic — no SSH process, no network.
    const calls: string[] = [];
    const remote = {
      sshRunStreaming: (cmd: string) => calls.push(cmd),
    } as unknown as RemoteHost;

    pruneStaleDockerImages(remote);

    expect(calls).toEqual([PRUNE_COMMAND]);
  });
});
