/**
 * Tracker-agnostic interface for issue tracking systems.
 *
 * Identity model:
 *  - `id` (`ISS-N`): the internal, locally-generated, ALWAYS-PRESENT primary
 *    key for an issue. Stable across the issue's lifetime. The on-disk file
 *    is named `<id>.yml`. Every agent-facing surface (skills, MCP tools,
 *    dispatch prompts) refers to issues by `id` only — agents do not know
 *    that external trackers exist.
 *  - `external_id`: tracker-native id (e.g. Trello card id). Empty when the
 *    issue has not been pushed to any external tracker (memory tracker,
 *    pre-create draft). Only the sync layer and tracker implementations
 *    consume `external_id`; never expose it to agents.
 *
 * Tracker implementations (TrelloTracker, MemoryTracker) translate the YAML
 * schema's status / type values to backend-native concepts (list IDs, label
 * IDs) internally. No tracker-native concepts leak through this interface.
 *
 * The IssueTracker methods continue to take `externalId` as their lookup key
 * because that IS the tracker's native concept. Higher layers map `id ↔
 * external_id` via the YAML's two id fields.
 */

export type IssueStatus =
  | "Review"
  | "ToDo"
  | "In Progress"
  | "Needs Help"
  | "Done"
  | "Cancelled";

export type IssueType = "Epic" | "Bug" | "Feature";

export type PhaseStatus = "Pending" | "Complete" | "Blocked";

export interface IssueRef {
  /** Internal id (`ISS-N`). Empty for refs from a tracker that has not yet been reconciled with a local YAML. */
  id: string;
  external_id: string;
  title: string;
  status: IssueStatus;
  /**
   * Tracker-specific list / category the card lives in, when distinct from
   * `status`. Today the only consumer is `Trello` Action Items: cards on the
   * Action Items list surface with `status: "ToDo"` (so they can become
   * blockers / be promoted by an operator) but `list_kind: "action_items"`
   * so the poller dispatch path skips them. Memory tracker leaves it
   * undefined. Adding a new kind is purely additive — existing consumers
   * default to dispatch-eligible when the field is absent.
   */
  list_kind?: "todo" | "action_items";
}

export interface IssueAcItem {
  check_item_id: string;
  title: string;
  checked: boolean;
}

export interface IssuePhase {
  check_item_id: string;
  title: string;
  status: PhaseStatus;
  notes: string;
}

export interface IssueComment {
  /** Tracker-native id; absent for local-only comments not yet pushed. */
  id?: string;
  author: string;
  timestamp: string;
  text: string;
}

export interface IssueTriaged {
  timestamp: string;
  status: string;
  explain: string;
}

export interface IssueRetro {
  good: string;
  bad: string;
  /**
   * IDs (`ISS-N`) of pre-existing issue cards filed as action items by the
   * agent during this card's lifecycle. The agent MUST create each action
   * item card via `danx_issue_create` (with full title + description + ac)
   * BEFORE pushing the resulting `ISS-N` here. The worker NEVER spawns cards
   * from this field; on terminal save it just resolves each id to the
   * corresponding issue's `title` for the rendered retro comment. Unknown
   * ids surface as `<ISS-N: unknown>` in the comment so a typo is loud, not
   * silent.
   */
  action_item_ids: string[];
  commits: string[];
}

/**
 * Blocked-state record. Populated when an in-progress card cannot proceed
 * because it is waiting on other in-flight work (a phase sibling, an Action
 * Items card, a separately-scoped task), but does NOT need human
 * intervention. The poller auto-clears `blocked` and dispatches the card
 * once every issue id in `by[]` reaches a terminal status (Done or
 * Cancelled).
 *
 * Distinct from `status: "Needs Help"`, which means a human must act
 * (credentials, deploy, ambiguous spec, write-only repo). Cards waiting on
 * other work go to `blocked`, not Needs Help.
 *
 * Invariants enforced by `validateIssue`:
 *  - `reason` non-empty.
 *  - `timestamp` non-empty (caller supplies ISO 8601; the validator does not
 *    parse the format).
 *  - `by[]` non-empty, every entry matches `ISS-<positive integer>`.
 *
 * When the agent has no existing card to point at, it MUST create one
 * (`danx_issue_create`) describing the unblock work and put that new id in
 * `by[]` — the field is never empty.
 */
export interface IssueBlocked {
  reason: string;
  timestamp: string;
  by: string[];
}

export interface Issue {
  schema_version: 3;
  tracker: string;
  /**
   * Internal primary id (`ISS-N`). Required, non-empty, locally generated by
   * `nextIssueId` from `./id-generator.ts`. Stable across the issue's
   * lifetime. The on-disk filename is `<id>.yml`. Agents only ever see this.
   */
  id: string;
  /**
   * Tracker-native id (e.g. Trello card id). Empty string when not synced
   * to any external tracker (memory tracker, pre-create draft, or a local
   * issue that will never push). Only the sync layer + tracker
   * implementations consume this — never expose it to agents.
   */
  external_id: string;
  /**
   * `parent_id` and `dispatch_id` are local-only metadata managed by the
   * poller and the danx_issue_create flow. `parent_id` references the
   * parent issue's `id` (NOT `external_id`). The tracker abstraction has
   * no place to store them, so sync passes them through verbatim.
   */
  parent_id: string | null;
  /**
   * Child issue ids (`ISS-N[]`). Populated only on Epic-typed issues whose
   * phases are split into separate cards. Reverse linkage to `parent_id`:
   * each entry in `children` MUST have its own YAML with
   * `parent_id == <this.id>`. Empty for non-epics and for epics whose phases
   * live as in-card checklist items rather than separate cards. Local-only
   * metadata; not synced to any external tracker (parallel to `parent_id`).
   * Maintained by the `danx-epic-link` skill on first epic pickup and by
   * the `danx_issue_create` flow when a new phase card is created.
   */
  children: string[];
  dispatch_id: string | null;
  status: IssueStatus;
  type: IssueType;
  title: string;
  description: string;
  triaged: IssueTriaged;
  ac: IssueAcItem[];
  phases: IssuePhase[];
  comments: IssueComment[];
  retro: IssueRetro;
  /**
   * Non-null = the card is waiting on the issues listed in `blocked.by[]`.
   * Worker forces `status: "ToDo"` whenever this is non-null; poller skips
   * dispatching the card until every blocker in `by[]` reaches a terminal
   * status (Done or Cancelled), at which point the poller clears
   * `blocked` and resumes dispatch. See `IssueBlocked` for the invariants.
   */
  blocked: IssueBlocked | null;
}

/**
 * Input shape for createCard — every Issue field that the caller can choose
 * minus the tracker-assigned ids (external_id, check_item_ids).
 *
 * `id` is REQUIRED here because it is locally generated BEFORE the tracker
 * push — the worker assigns the next `ISS-N` to a draft, then asks the
 * tracker to create a card with title prefixed `#<id>: <title>`.
 */
export interface CreateCardInput {
  schema_version: 3;
  tracker: string;
  id: string;
  parent_id: string | null;
  children: string[];
  status: IssueStatus;
  type: IssueType;
  title: string;
  description: string;
  triaged: IssueTriaged;
  ac: Array<{ title: string; checked: boolean }>;
  phases: Array<{ title: string; status: PhaseStatus; notes: string }>;
  comments: IssueComment[];
  retro: IssueRetro;
  /**
   * Optional on input — `createCard` always stores `blocked: null` on the
   * fresh card. Agents add the `blocked` record via subsequent saves.
   */
  blocked?: IssueBlocked | null;
}

export interface IssueTracker {
  fetchOpenCards(): Promise<IssueRef[]>;

  getCard(externalId: string): Promise<Issue>;

  createCard(input: CreateCardInput): Promise<{
    external_id: string;
    ac: { check_item_id: string }[];
    phases: { check_item_id: string }[];
  }>;

  /**
   * Patch the card's title / description. When `patch.title` is supplied,
   * the caller SHOULD also supply `patch.id` so tracker implementations
   * that prefix the title with `#<id>: ` (Trello) preserve the prefix
   * without a read round-trip. Implementations that don't prefix titles
   * (memory) ignore `patch.id`.
   */
  updateCard(
    externalId: string,
    patch: { title?: string; description?: string; id?: string },
  ): Promise<void>;

  moveToStatus(externalId: string, status: IssueStatus): Promise<void>;

  setLabels(
    externalId: string,
    labels: {
      type: IssueType;
      needsHelp: boolean;
      triaged: boolean;
      blocked: boolean;
    },
  ): Promise<void>;

  addComment(
    externalId: string,
    text: string,
  ): Promise<{ id: string; timestamp: string }>;

  /**
   * Replace the body of an existing tracker comment in-place.
   *
   * Used by the worker-side retro renderer to keep ONE retro comment per
   * card lifetime — when retro fields change between saves, we EDIT the
   * existing comment rather than POST a duplicate. `commentId` is the
   * tracker-native id returned by `addComment` / `getComments`.
   *
   * Implementations MUST preserve the comment's tracker-native author and
   * timestamp; only the text is replaced. Throw if the comment does not
   * exist on the given card.
   */
  editComment(
    externalId: string,
    commentId: string,
    text: string,
  ): Promise<void>;

  getComments(
    externalId: string,
  ): Promise<
    Array<{ id: string; author: string; timestamp: string; text: string }>
  >;

  addAcItem(
    externalId: string,
    item: { title: string; checked: boolean },
  ): Promise<{ check_item_id: string }>;

  updateAcItem(
    externalId: string,
    checkItemId: string,
    patch: { title?: string; checked?: boolean },
  ): Promise<void>;

  deleteAcItem(externalId: string, checkItemId: string): Promise<void>;

  addPhaseItem(
    externalId: string,
    item: { title: string; status: PhaseStatus; notes: string },
  ): Promise<{ check_item_id: string }>;

  updatePhaseItem(
    externalId: string,
    checkItemId: string,
    patch: { title?: string; status?: PhaseStatus; notes?: string },
  ): Promise<void>;

  deletePhaseItem(externalId: string, checkItemId: string): Promise<void>;
}

export const ISSUE_STATUSES: readonly IssueStatus[] = [
  "Review",
  "ToDo",
  "In Progress",
  "Needs Help",
  "Done",
  "Cancelled",
] as const;

export const ISSUE_TYPES: readonly IssueType[] = [
  "Epic",
  "Bug",
  "Feature",
] as const;

export const PHASE_STATUSES: readonly PhaseStatus[] = [
  "Pending",
  "Complete",
  "Blocked",
] as const;
