/**
 * Multi-environment dispatch lock for issue cards.
 *
 * Problem: a single tracker card (Trello) can be picked up independently by
 * multiple poller instances running in different environments (e.g. local
 * dev workstation + production EC2 worker). Each instance writes its OWN
 * local YAML at `<repo>/.danxbot/issues/open/<id>.yml`, dispatches an
 * agent against it, and then `sync.ts` pushes the diff back to the tracker
 * — silently overwriting the other instance's changes.
 *
 * Solution: a single, idempotent "dispatch lock" comment on the tracker
 * card. Before claiming a card, every poller instance:
 *   1. Reads card comments.
 *   2. Looks for a comment carrying `LOCK_COMMENT_MARKER`.
 *   3. If present and < `LOCK_TTL_MS` old AND held by a different
 *      `holder/host` pair → refuse the claim. Caller logs + skips this
 *      tick; the next tick re-tries.
 *   4. If absent → POST a fresh lock comment.
 *   5. If stale (>= TTL) or held by self → EDIT the existing comment
 *      in-place with new dispatch metadata. One comment per card lifetime.
 *
 * The comment ALSO serves as the dispatch traceability record: it carries
 * the dispatch UUID + the JSONL directory path on the holder's host, so
 * "find the agent session that worked this card" reduces to one `grep -l`
 * across that directory.
 *
 * No active release on dispatch completion. Lock release is lazy via TTL
 * — the next poller tick that wants the card sees the stale lock and
 * reclaims it. This keeps the lock semantics symmetric across crashes,
 * timeouts, and clean completions.
 *
 * The lock comment is `DANXBOT_COMMENT_MARKER`-prefixed so the poller's
 * own `isUserResponse` filter ignores it, AND `LOCK_COMMENT_MARKER`-
 * prefixed so `parseLockComment` and the sync layer's identity checks can
 * find it deterministically.
 */

import { hostname, homedir } from "node:os";
import { DANXBOT_COMMENT_MARKER } from "../poller/constants.js";
import { createLogger } from "../logger.js";
import { type IssueTracker } from "./interface.js";

const log = createLogger("dispatch-lock");

/** Marker line identifying this comment as the dispatch lock. */
export const LOCK_COMMENT_MARKER = "<!-- danxbot-lock -->";

/** Lock lifetime. After this, a different holder may reclaim. */
export const LOCK_TTL_MS = 2 * 60 * 60 * 1000;

/**
 * Single source of truth for the lock comment's table rows: the
 * Markdown writer (`renderLockComment`) and the parser regex consume
 * THIS list, so renaming a row touches one site instead of two. The
 * ordering is the on-disk render order; reorderings are cosmetic and
 * roundtrip cleanly through `parseLockComment`.
 */
export const LOCK_FIELDS = [
  "holder",
  "host",
  "dispatch_id",
  "repo_path",
  "jsonl_dir",
  "workspace",
  "started_at",
  "ttl",
  "stale_after",
] as const;
export type LockField = (typeof LOCK_FIELDS)[number];

/**
 * Identity of the poller instance attempting to acquire the lock. Two
 * different `LockHolderInfo` values are considered "the same holder" iff
 * BOTH `holder` and `host` match.
 *
 * `holder` is the env identifier (e.g. `gpt`, `local-newms-laptop`).
 * Conventionally `process.env.DANXBOT_TARGET ?? os.hostname()`.
 *
 * `host` is the physical host identifier (hostname or IP) — distinguishes
 * two instances that share a `holder` but run on different hardware (rare
 * in practice but cheap to record).
 *
 * `dispatchId` is the per-dispatch UUID generated by the poller; it goes
 * into the lock comment as the traceability key. `find session` greps the
 * holder's `jsonlDir` for this UUID.
 */
export interface LockHolderInfo {
  holder: string;
  host: string;
  dispatchId: string;
  repoPath: string;
  jsonlDir: string;
  workspace: string;
}

/** Parsed lock-comment metadata. `commentId` is the tracker-native id. */
export interface ParsedLock {
  holder: string;
  host: string;
  dispatchId: string;
  repoPath: string;
  jsonlDir: string;
  workspace: string;
  startedAt: string;
  commentId: string;
}

export interface AcquireResult {
  acquired: boolean;
  comment: { id: string; text: string; timestamp: string };
  /** When `acquired === false`, the holder currently in possession. */
  existing?: ParsedLock;
  /** True when an existing lock was reclaimed because it was stale. */
  reclaimed?: boolean;
  /** True when the same holder re-acquired its own (still-fresh) lock. */
  refreshed?: boolean;
}

/**
 * Render a lock comment body. Output is deterministic for a given
 * `(info, startedAt, ttlMs)` triple so the sync layer's
 * identity-by-text check short-circuits on no-op refreshes.
 *
 * Format is a Markdown table because the same comment is shown in the
 * Trello UI to humans inspecting card history.
 */
export function renderLockComment(
  info: LockHolderInfo,
  startedAt: string,
  ttlMs: number = LOCK_TTL_MS,
): string {
  const staleAt = new Date(new Date(startedAt).getTime() + ttlMs).toISOString();
  const ttlLabel = `${Math.round(ttlMs / 60000)}m`;
  const values: Record<LockField, string> = {
    holder: info.holder,
    host: info.host,
    dispatch_id: info.dispatchId,
    repo_path: info.repoPath,
    jsonl_dir: info.jsonlDir,
    workspace: info.workspace,
    started_at: startedAt,
    ttl: ttlLabel,
    stale_after: staleAt,
  };
  const tableRows = LOCK_FIELDS.map(
    (field) => `| ${field} | \`${values[field]}\` |`,
  ).join("\n");
  return `${DANXBOT_COMMENT_MARKER}
${LOCK_COMMENT_MARKER}

**Dispatch lock**

| Field | Value |
|---|---|
${tableRows}

To find the agent session that worked this card:
\`\`\`
grep -l '${info.dispatchId}' ${info.jsonlDir}/*.jsonl
\`\`\``;
}

/**
 * Parse a comment body into structured lock fields. Returns `null` when
 * the comment does not carry `LOCK_COMMENT_MARKER` or when required
 * fields (`holder`, `dispatch_id`, `started_at`) are missing — caller
 * treats `null` as "lock comment is corrupt; reclaim".
 */
export function parseLockComment(
  text: string,
  commentId: string,
): ParsedLock | null {
  if (!text.includes(LOCK_COMMENT_MARKER)) return null;
  const fields: Record<string, string> = {};
  // Captures rows of the shape `| <field> | `<value>` |`. Field names
  // come from `LOCK_FIELDS` — the regex matches `[a-z_]+` so unknown
  // names are tolerated (forward-compat with future fields) but only
  // declared `LOCK_FIELDS` are surfaced on the returned `ParsedLock`.
  const rowRe = /^\| ([a-z_]+) \| `([^`]*)` \|$/gm;
  let m: RegExpExecArray | null;
  while ((m = rowRe.exec(text)) !== null) {
    fields[m[1]] = m[2];
  }
  if (!fields.holder || !fields.dispatch_id || !fields.started_at) {
    return null;
  }
  return {
    holder: fields.holder,
    host: fields.host ?? "",
    dispatchId: fields.dispatch_id,
    repoPath: fields.repo_path ?? "",
    jsonlDir: fields.jsonl_dir ?? "",
    workspace: fields.workspace ?? "",
    startedAt: fields.started_at,
    commentId,
  };
}

/**
 * Attempt to acquire the dispatch lock for `externalId`.
 *
 * Returns `{ acquired: true }` when the caller may proceed to dispatch.
 * Returns `{ acquired: false, existing }` when another holder owns the
 * card within TTL — caller logs + skips this tick.
 *
 * Side effects on `acquired: true`:
 *   - No existing lock → POSTs a new comment.
 *   - Stale lock → EDITS in-place (`reclaimed: true`).
 *   - Self-held fresh lock → EDITS in-place (`refreshed: true`) so
 *     `dispatchId` and `startedAt` reflect the new run.
 */
export async function tryAcquireLock(
  tracker: IssueTracker,
  externalId: string,
  info: LockHolderInfo,
  now: Date = new Date(),
  ttlMs: number = LOCK_TTL_MS,
): Promise<AcquireResult> {
  const comments = await tracker.getComments(externalId);
  const existingComment = comments.find((c) =>
    c.text.includes(LOCK_COMMENT_MARKER),
  );
  const startedAt = now.toISOString();
  const text = renderLockComment(info, startedAt, ttlMs);

  if (!existingComment) {
    const r = await tracker.addComment(externalId, text);
    return {
      acquired: true,
      comment: { id: r.id, text, timestamp: r.timestamp },
    };
  }

  const parsed = parseLockComment(existingComment.text, existingComment.id);
  if (!parsed) {
    // The comment carries `LOCK_COMMENT_MARKER` but does not parse —
    // either schema drift between worker versions or a manual edit on
    // the tracker UI. Stomping it is the recovery path (otherwise the
    // card stays unlockable forever); log loudly so an operator sees
    // the corruption signal in worker logs.
    log.warn(
      `lock comment for ${externalId} has marker but unparseable body — overwriting (potential schema drift or manual edit). Original commentId=${existingComment.id}`,
    );
    await tracker.editComment(externalId, existingComment.id, text);
    return {
      acquired: true,
      reclaimed: true,
      comment: {
        id: existingComment.id,
        text,
        timestamp: existingComment.timestamp,
      },
    };
  }

  const ageMs = now.getTime() - new Date(parsed.startedAt).getTime();
  const isStale = ageMs >= ttlMs;
  const isSelf = parsed.holder === info.holder && parsed.host === info.host;

  if (!isStale && !isSelf) {
    return {
      acquired: false,
      existing: parsed,
      comment: {
        id: existingComment.id,
        text: existingComment.text,
        timestamp: existingComment.timestamp,
      },
    };
  }

  await tracker.editComment(externalId, existingComment.id, text);
  return {
    acquired: true,
    reclaimed: isStale && !isSelf,
    refreshed: isSelf,
    comment: {
      id: existingComment.id,
      text,
      timestamp: existingComment.timestamp,
    },
  };
}

/**
 * Build a `LockHolderInfo` for the current poller instance and dispatch.
 *
 * `holder` is the active deployment-target name (e.g. `danxbot-production`,
 * `local`) — passed in from `config.targetName` rather than read from the
 * environment so the env-var surface lives in one place. Falls back to the
 * OS hostname only when the target name is empty (guards against a future
 * code path that bypasses the config layer).
 *
 * `host` is always the OS hostname — distinguishes two pollers that share a
 * `holder` but run on different hardware (rare but cheap to record).
 *
 * `jsonlDir` matches Claude Code's slug convention: the dispatched agent's
 * cwd path with every `/` replaced by `-`, prefixed under
 * `~/.claude/projects/`. Uses `os.homedir()` so the path resolves correctly
 * for whichever user the poller runs as (no `process.env.HOME` magic-string
 * fallback). The directory goes into the lock comment so a debugger can
 * `grep -l '<dispatchId>' <jsonlDir>/*.jsonl` to locate the agent session.
 */
export function buildLockHolderInfo(args: {
  targetName: string;
  repoPath: string;
  workspace: string;
  dispatchId: string;
}): LockHolderInfo {
  const host = hostname();
  const cwd = `${args.repoPath}/.danxbot/workspaces/${args.workspace}`;
  const slug = cwd.replaceAll("/", "-");
  const jsonlDir = `${homedir()}/.claude/projects/${slug}`;
  return {
    holder: args.targetName || host,
    host,
    dispatchId: args.dispatchId,
    repoPath: args.repoPath,
    jsonlDir,
    workspace: args.workspace,
  };
}
