import {
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  unlinkSync,
  chmodSync,
} from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { config, repoContexts } from "../config.js";
import { getReposBase, REVIEW_MIN_CARDS, DANXBOT_COMMENT_MARKER, SCRIPT_PROMPTS } from "./constants.js";
import { parseSimpleYaml } from "./parse-yaml.js";
import { createLogger } from "../logger.js";
import { spawnInTerminal } from "../terminal.js";
import { spawnHeadlessAgent } from "../agent/launcher.js";
import {
  fetchTodoCards,
  fetchNeedsHelpCards,
  fetchReviewCards,
  fetchLatestComment,
  moveCardToList,
  isUserResponse,
} from "./trello-client.js";
import type { RepoContext, TrelloConfig } from "../types.js";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

const log = createLogger("poller");

/** Per-repo poller state */
interface RepoPollerState {
  teamRunning: boolean;
  polling: boolean;
  lockFile: string;
  lockCheckId: ReturnType<typeof setInterval> | null;
  intervalId: ReturnType<typeof setInterval> | null;
}

const repoState = new Map<string, RepoPollerState>();

function getState(repoName: string): RepoPollerState {
  let state = repoState.get(repoName);
  if (!state) {
    state = {
      teamRunning: false,
      polling: false,
      lockFile: resolve(projectRoot, `.poller-running-${repoName}`),
      lockCheckId: null,
      intervalId: null,
    };
    repoState.set(repoName, state);
  }
  return state;
}

/**
 * Check Needs Help cards for user responses. Cards where a user has replied
 * (latest comment lacks the danxbot marker) are moved to the top of ToDo
 * so they get higher priority than existing ToDo cards.
 */
async function checkNeedsHelp(trello: TrelloConfig): Promise<number> {
  let cards;
  try {
    cards = await fetchNeedsHelpCards(trello);
  } catch (error) {
    log.error("Error fetching Needs Help cards", error);
    return 0;
  }

  if (cards.length === 0) return 0;

  let movedCount = 0;
  for (const card of cards) {
    try {
      const latestComment = await fetchLatestComment(trello, card.id);
      if (isUserResponse(latestComment)) {
        log.info(`User responded on "${card.name}" — moving to ToDo`);
        await moveCardToList(trello, card.id, trello.todoListId, "top");
        movedCount++;
      }
    } catch (error) {
      log.error(`Error checking comments for card "${card.name}"`, error);
    }
  }

  return movedCount;
}

export async function poll(repo: RepoContext): Promise<void> {
  const state = getState(repo.name);
  if (state.teamRunning || state.polling) {
    return;
  }

  state.polling = true;
  try {
    await _poll(repo);
  } finally {
    state.polling = false;
  }
}

async function _poll(repo: RepoContext): Promise<void> {
  // Sync danxbot config into target repo on every poll cycle
  syncRepoFiles(repo);

  // Write Trello config into target repo's rules
  const repoRulesDir = resolve(repo.localPath, ".claude/rules");
  mkdirSync(repoRulesDir, { recursive: true });
  writeTrelloConfigRule(repo.trello, repoRulesDir);

  log.info(`[${repo.name}] Checking Needs Help + ToDo lists...`);

  // Check Needs Help first — user-responded cards get moved to ToDo top
  const movedFromNeedsHelp = await checkNeedsHelp(repo.trello);
  if (movedFromNeedsHelp > 0) {
    log.info(
      `[${repo.name}] Moved ${movedFromNeedsHelp} card${movedFromNeedsHelp > 1 ? "s" : ""} from Needs Help to ToDo`,
    );
  }

  let cards;
  try {
    cards = await fetchTodoCards(repo.trello);
  } catch (error) {
    log.error(`[${repo.name}] Error fetching cards`, error);
    return;
  }

  if (cards.length === 0) {
    log.info(`[${repo.name}] No cards in ToDo — checking if ideator needed`);
    await checkAndSpawnIdeator(repo);
    return;
  }

  log.info(
    `[${repo.name}] Found ${cards.length} card${cards.length > 1 ? "s" : ""} — starting team`,
  );
  cards.forEach((card, i) => log.info(`  ${i + 1}. ${card.name}`));

  spawnClaude(repo, "Danxbot Team", "run-team.sh");
}

/** Directory containing files to inject into target repos. */
const injectDir = resolve(dirname(fileURLToPath(import.meta.url)), "inject");

/**
 * Write the Trello config rule file into the target repo so the spawned
 * Claude agent always has the correct IDs — even after context compaction.
 * Generated from the repo's TrelloConfig, making it the single source of truth.
 */
function writeTrelloConfigRule(trello: TrelloConfig, repoRulesDir: string): void {
  const content = `# Trello Config (auto-generated — do not edit)

This file is generated by the danxbot poller from environment variables before each run.

## Board

Board ID: \`${trello.boardId}\`

## Lists

| List | ID |
|------|----|
| Review | \`${trello.reviewListId}\` |
| ToDo | \`${trello.todoListId}\` |
| In Progress | \`${trello.inProgressListId}\` |
| Needs Help | \`${trello.needsHelpListId}\` |
| Done | \`${trello.doneListId}\` |
| Cancelled | \`${trello.cancelledListId}\` |
| Action Items | \`${trello.actionItemsListId}\` |

## Labels

| Label | ID |
|-------|----|
| Bug | \`${trello.bugLabelId}\` |
| Feature | \`${trello.featureLabelId}\` |
| Epic | \`${trello.epicLabelId}\` |
| Needs Help | \`${trello.needsHelpLabelId}\` |
`;

  writeFileSync(resolve(repoRulesDir, "danx-trello-config.md"), content);
}

/**
 * Validate that .danxbot/config/ in the connected repo and env vars are fully configured.
 * Throws if anything is missing or empty — the poller must not run without valid config.
 */
export function validateRepoConfig(repo: RepoContext): void {
  const errors: string[] = [];
  const danxbotConfigDir = resolve(repo.localPath, ".danxbot/config");

  // 1. .danxbot/config/ directory must exist in the connected repo
  if (!existsSync(danxbotConfigDir)) {
    throw new Error(
      `[${repo.name}] .danxbot/config/ not found in connected repo. Run ./install.sh to set up danxbot.`,
    );
  }

  // 2. Required files must exist and not be empty
  const requiredFiles = [
    { path: "config.yml", label: "Repo configuration" },
    { path: "overview.md", label: "Repo overview" },
    { path: "workflow.md", label: "Repo workflow" },
    { path: "trello.yml", label: "Trello board/list/label IDs" },
  ];

  for (const { path, label } of requiredFiles) {
    const fullPath = resolve(danxbotConfigDir, path);
    if (!existsSync(fullPath)) {
      errors.push(`Missing .danxbot/config/${path} (${label})`);
    } else {
      const content = readFileSync(fullPath, "utf-8").trim();
      if (!content) {
        errors.push(`Empty .danxbot/config/${path} (${label})`);
      }
    }
  }

  // 3. config.yml must have required fields with non-empty values
  const repoConfigYml = resolve(danxbotConfigDir, "config.yml");
  if (existsSync(repoConfigYml)) {
    const raw = readFileSync(repoConfigYml, "utf-8");
    const cfg = parseSimpleYaml(raw);

    const requiredFields = [
      { key: "name", label: "Repo name" },
      { key: "url", label: "Repo URL" },
      { key: "runtime", label: "Runtime (docker or local)" },
      { key: "language", label: "Language" },
    ];

    for (const { key, label } of requiredFields) {
      if (!cfg[key] || !cfg[key].trim()) {
        errors.push(
          `Missing '${key}' in .danxbot/config/config.yml (${label})`,
        );
      }
    }

    // If runtime is docker, compose config is required
    if (cfg.runtime === "docker") {
      const dockerFields = [
        { key: "docker.compose_file", label: "Docker compose file" },
        { key: "docker.service_name", label: "Docker service name" },
        { key: "docker.project_name", label: "Docker project name" },
      ];
      for (const { key, label } of dockerFields) {
        if (!cfg[key] || !cfg[key].trim()) {
          errors.push(
            `Missing '${key}' in .danxbot/config/config.yml (${label} — required when runtime is docker)`,
          );
        }
      }

      // Compose file must actually exist
      const composeFile = resolve(danxbotConfigDir, "compose.yml");
      if (!existsSync(composeFile)) {
        errors.push(
          `Missing .danxbot/config/compose.yml (required when runtime is docker)`,
        );
      }
    }
  }

  // 4. Required environment variables (secrets)
  const requiredEnvVars = [
    { name: "ANTHROPIC_API_KEY", label: "Anthropic API key" },
    { name: "REPOS", label: "Connected repos (name:url,...)" },
  ];

  for (const { name, label } of requiredEnvVars) {
    const value = process.env[name];
    if (!value || !value.trim()) {
      errors.push(`Missing env var ${name} (${label})`);
    }
  }

  // 5. Per-repo secrets must be set (loaded via RepoContext)
  if (!repo.trello.apiKey) errors.push(`Missing DANX_TRELLO_API_KEY in ${repo.name}/.danxbot/.env`);
  if (!repo.trello.apiToken) errors.push(`Missing DANX_TRELLO_API_TOKEN in ${repo.name}/.danxbot/.env`);
  if (!repo.githubToken) errors.push(`Missing DANX_GITHUB_TOKEN in ${repo.name}/.danxbot/.env`);

  // 6. Claude auth files must exist
  const claudeAuthDir = resolve(projectRoot, "claude-auth");
  const claudeJson = resolve(claudeAuthDir, ".claude.json");
  if (!existsSync(claudeJson)) {
    errors.push(
      `Missing claude-auth/.claude.json (Claude Code credentials — run ./install.sh Step 6)`,
    );
  }

  if (errors.length > 0) {
    throw new Error(
      `[${repo.name}] Repo config validation failed:\n  - ${errors.join("\n  - ")}\n\nRun ./install.sh to complete setup.`,
    );
  }

  log.info(`[${repo.name}] Repo config validated successfully`);
}

/**
 * Sync danxbot config into the target repo's .claude/ directory. All injected
 * files use the `danx-` prefix so they're clearly identifiable and gitignore-able.
 * Called on every poll cycle to keep targets up to date.
 */
function syncRepoFiles(repo: RepoContext): void {
  const danxbotConfigDir = resolve(repo.localPath, ".danxbot/config");
  if (!existsSync(danxbotConfigDir)) return;

  const repoDir = repo.localPath;
  const repoClaudeDir = resolve(repoDir, ".claude");
  const repoRulesDir = resolve(repoClaudeDir, "rules");
  const repoSkillsDir = resolve(repoClaudeDir, "skills");
  const repoToolsDir = resolve(repoClaudeDir, "tools");
  const overridesDir = resolve(projectRoot, "repo-overrides");

  mkdirSync(repoRulesDir, { recursive: true });
  mkdirSync(repoToolsDir, { recursive: true });

  // 1. Generate danx-repo-config.md from .danxbot/config/config.yml
  const repoConfigYml = resolve(danxbotConfigDir, "config.yml");
  const raw = readFileSync(repoConfigYml, "utf-8");
  const cfg = parseSimpleYaml(raw);

  const name = cfg.name || "unknown";
  const url = cfg.url || "";
  const runtime = cfg.runtime || "local";
  const language = cfg.language || "";
  const framework = cfg.framework || "";
  const testCmd = cfg["commands.test"] || "";
  const lintCmd = cfg["commands.lint"] || "";
  const typeCheckCmd = cfg["commands.type_check"] || "";
  const devCmd = cfg["commands.dev"] || "";
  const composeFile = cfg["docker.compose_file"] || "";
  const serviceName = cfg["docker.service_name"] || "";
  const projectName = cfg["docker.project_name"] || "";
  const sourcePath = cfg["paths.source"] || "";
  const testsPath = cfg["paths.tests"] || "";
  const gitMode = cfg.git_mode || "pr";

  let repoConfigContent = `# Repo Config (auto-generated by danxbot — do not edit)

## Repo

| Field | Value |
|-------|-------|
| Name | \`${name}\` |
| URL | \`${url}\` |
| Runtime | \`${runtime}\` |
| Language | \`${language}\` |
| Framework | \`${framework}\` |
| Git Mode | \`${gitMode}\` |

## Commands

| Command | Value |
|---------|-------|
| Test | \`${testCmd}\` |
| Lint | \`${lintCmd}\` |
| Type Check | \`${typeCheckCmd}\` |
| Dev | \`${devCmd}\` |

## Paths

| Path | Value |
|------|-------|
| Source | \`${sourcePath}\` |
| Tests | \`${testsPath}\` |
`;

  if (runtime === "docker" && composeFile) {
    repoConfigContent += `
## Docker

| Field | Value |
|-------|-------|
| Compose File | \`${composeFile}\` |
| Service Name | \`${serviceName}\` |
| Project Name | \`${projectName}\` |
`;
  }

  writeFileSync(resolve(repoRulesDir, "danx-repo-config.md"), repoConfigContent);

  // 2. Copy overview.md and workflow.md → danx-repo-overview.md / danx-repo-workflow.md
  for (const [src, dest] of [
    ["overview.md", "danx-repo-overview.md"],
    ["workflow.md", "danx-repo-workflow.md"],
  ] as const) {
    const srcPath = resolve(danxbotConfigDir, src);
    if (existsSync(srcPath)) {
      const header = `<!-- AUTO-GENERATED by danxbot from .danxbot/config/${src} — do not edit -->\n\n`;
      const body = readFileSync(srcPath, "utf-8");
      writeFileSync(resolve(repoRulesDir, dest), header + body);
    }
  }

  // 3. Copy repo-specific tools.md → .claude/rules/danx-tools.md
  const toolsDocSource = resolve(danxbotConfigDir, "tools.md");
  if (existsSync(toolsDocSource)) {
    copyFileSync(toolsDocSource, resolve(repoRulesDir, "danx-tools.md"));
  }

  // 4. Copy repo-specific tool scripts → .claude/tools/ (executable)
  const toolsScriptsSource = resolve(danxbotConfigDir, "tools");
  if (existsSync(toolsScriptsSource)) {
    for (const file of readdirSync(toolsScriptsSource)) {
      const src = resolve(toolsScriptsSource, file);
      const dest = resolve(repoToolsDir, file);
      copyFileSync(src, dest);
      try {
        chmodSync(dest, 0o755);
      } catch (e) {
        log.warn(`Failed to chmod ${dest}:`, e);
      }
    }
  }

  // 5. Inject danx-* skills from inject/skills/
  const injectSkillsDir = resolve(injectDir, "skills");
  if (existsSync(injectSkillsDir)) {
    for (const skillName of readdirSync(injectSkillsDir)) {
      const srcSkillDir = resolve(injectSkillsDir, skillName);
      const destSkillDir = resolve(repoSkillsDir, skillName);
      mkdirSync(destSkillDir, { recursive: true });
      for (const file of readdirSync(srcSkillDir)) {
        copyFileSync(resolve(srcSkillDir, file), resolve(destSkillDir, file));
      }
    }
  }

  // 6. Inject danx-* tools from inject/tools/
  const injectToolsDir = resolve(injectDir, "tools");
  if (existsSync(injectToolsDir)) {
    for (const file of readdirSync(injectToolsDir)) {
      const src = resolve(injectToolsDir, file);
      const dest = resolve(repoToolsDir, file);
      copyFileSync(src, dest);
      try {
        chmodSync(dest, 0o755);
      } catch (e) {
        log.warn(`Failed to chmod ${dest}:`, e);
      }
    }
  }

  // 7. Copy compose override to repo-overrides/ (optional)
  const composeSource = resolve(danxbotConfigDir, "compose.yml");
  if (existsSync(composeSource)) {
    mkdirSync(overridesDir, { recursive: true });
    copyFileSync(composeSource, resolve(overridesDir, `${name}-compose.yml`));
  }

  // 8. Copy post-clone hook to repo-overrides/ (optional)
  const hookSource = resolve(danxbotConfigDir, "post-clone.sh");
  if (existsSync(hookSource)) {
    mkdirSync(overridesDir, { recursive: true });
    copyFileSync(hookSource, resolve(overridesDir, `post-clone-${name}.sh`));
  }

  // 9. Copy docs/ → danxbot docs dir (domains and schema)
  const repoDocsDir = resolve(danxbotConfigDir, "docs");
  if (existsSync(repoDocsDir)) {
    const docsDir = resolve(projectRoot, "docs");
    for (const subdir of ["domains", "schema"]) {
      const srcDir = resolve(repoDocsDir, subdir);
      if (!existsSync(srcDir)) continue;
      const destDir = resolve(docsDir, subdir);
      mkdirSync(destDir, { recursive: true });
      for (const file of readdirSync(srcDir)) {
        copyFileSync(resolve(srcDir, file), resolve(destDir, file));
      }
    }
  }

  // 10. Copy .danxbot/features.md → docs/features.md (only if not already present)
  const danxbotDir = resolve(danxbotConfigDir, "..");
  const featuresSource = resolve(danxbotDir, "features.md");
  const featuresDest = resolve(projectRoot, "docs", "features.md");
  if (existsSync(featuresSource) && !existsSync(featuresDest)) {
    mkdirSync(resolve(projectRoot, "docs"), { recursive: true });
    copyFileSync(featuresSource, featuresDest);
  }
}

function spawnClaude(repo: RepoContext, title: string, scriptName: string): void {
  const state = getState(repo.name);

  // Safety net: refuse to spawn if lock file already exists (race condition guard)
  if (existsSync(state.lockFile)) {
    log.error(`[${repo.name}] Lock file exists but teamRunning was false — refusing to spawn`);
    return;
  }

  state.teamRunning = true;

  // Lock file signals that the team is running.
  writeFileSync(state.lockFile, String(process.pid));

  if (config.isHost) {
    // Host mode: open a Windows Terminal tab with the shell script.
    // The script removes the lock file via EXIT trap.
    const script = resolve(dirname(fileURLToPath(import.meta.url)), scriptName);
    spawnInTerminal({ title: `${title} [${repo.name}]`, script, cwd: projectRoot, env: { ...process.env, DANXBOT_REPO_NAME: repo.name } });
    startLockWatch(repo);
  } else {
    // Docker mode: spawn a headless claude CLI process.
    // Completion is handled by the onComplete callback.
    const prompt = SCRIPT_PROMPTS[scriptName];
    if (!prompt) {
      throw new Error(`No prompt mapping for script: ${scriptName}`);
    }

    spawnHeadlessAgent({
      prompt,
      repoName: repo.name,
      timeoutMs: config.pollerIntervalMs * 60, // generous timeout: 60x poll interval
      env: {
        DANXBOT_REPO_NAME: repo.name,
        DANXBOT_EPHEMERAL: "1",
        DANXBOT_PROJECT_ROOT: projectRoot,
      },
      onComplete: () => {
        log.info(`[${repo.name}] Headless agent finished — resuming polling`);
        state.teamRunning = false;
        try {
          if (existsSync(state.lockFile)) unlinkSync(state.lockFile);
        } catch (e) {
          log.warn(`[${repo.name}] Failed to remove lock file after headless agent`, e);
        }
        poll(repo).catch((err) =>
          log.error(`[${repo.name}] Re-poll after headless agent failed`, err),
        );
      },
    });
  }
}

async function checkAndSpawnIdeator(repo: RepoContext): Promise<void> {
  let reviewCards;
  try {
    reviewCards = await fetchReviewCards(repo.trello);
  } catch (error) {
    log.error(`[${repo.name}] Error fetching Review cards`, error);
    return;
  }

  if (reviewCards.length >= REVIEW_MIN_CARDS) {
    log.info(
      `[${repo.name}] Review has ${reviewCards.length} cards (min ${REVIEW_MIN_CARDS}) — no ideation needed`,
    );
    return;
  }

  log.info(
    `[${repo.name}] Review has ${reviewCards.length} cards (min ${REVIEW_MIN_CARDS}) — spawning ideator`,
  );
  spawnClaude(repo, "Danxbot Ideator", "run-ideator.sh");
}

export function shutdown(): void {
  log.info("Shutting down...");

  for (const [repoName, state] of repoState) {
    if (state.intervalId) {
      clearInterval(state.intervalId);
      state.intervalId = null;
    }

    if (state.lockCheckId) {
      clearInterval(state.lockCheckId);
      state.lockCheckId = null;
    }

    // Only remove lock file if no team is running
    if (state.teamRunning) {
      log.info(`[${repoName}] Team is running — leaving lock file for script to clean up`);
    } else {
      try {
        if (existsSync(state.lockFile)) unlinkSync(state.lockFile);
      } catch (e) {
        log.warn(`[${repoName}] Failed to remove lock file`, e);
      }
    }
  }

  process.exit(0);
}

function startLockWatch(repo: RepoContext): void {
  const state = getState(repo.name);
  state.lockCheckId = setInterval(() => {
    if (!existsSync(state.lockFile)) {
      clearInterval(state.lockCheckId!);
      state.lockCheckId = null;
      log.info(`[${repo.name}] Team finished — resuming polling`);
      state.teamRunning = false;
      poll(repo).catch((err) =>
        log.error(`[${repo.name}] Re-poll after team completion failed`, err),
      );
    }
  }, 5000);
}

export function start(): void {
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  if (repoContexts.length === 0) {
    log.error("No repos configured — nothing to poll");
    return;
  }

  // Validate and start polling for each repo independently
  for (const repo of repoContexts) {
    validateRepoConfig(repo);

    const state = getState(repo.name);
    const intervalSeconds = config.pollerIntervalMs / 1000;
    log.info(`[${repo.name}] Started — polling every ${intervalSeconds}s`);

    // Remove stale lock file from a previous run
    if (existsSync(state.lockFile)) {
      log.warn(`[${repo.name}] Stale lock file found — removing`);
      unlinkSync(state.lockFile);
    }

    poll(repo);
    state.intervalId = setInterval(() => poll(repo), config.pollerIntervalMs);
  }
}

/** Reset module state for testing. Do not use in production. */
export function _resetForTesting(): void {
  for (const state of repoState.values()) {
    state.teamRunning = false;
    state.polling = false;
    if (state.intervalId) {
      clearInterval(state.intervalId);
      state.intervalId = null;
    }
    if (state.lockCheckId) {
      clearInterval(state.lockCheckId);
      state.lockCheckId = null;
    }
  }
  repoState.clear();
}

// Auto-start when run as the direct entrypoint.
const isDirectEntrypoint =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("src/poller/index.ts");

if (isDirectEntrypoint) {
  start();
}
