import {
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  unlinkSync,
  chmodSync,
} from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  config,
  TODO_LIST_ID,
  REVIEW_MIN_CARDS,
  BOARD_ID,
  REVIEW_LIST_ID,
  IN_PROGRESS_LIST_ID,
  NEEDS_HELP_LIST_ID,
  DONE_LIST_ID,
  CANCELLED_LIST_ID,
  ACTION_ITEMS_LIST_ID,
  BUG_LABEL_ID,
  FEATURE_LABEL_ID,
  EPIC_LABEL_ID,
  NEEDS_HELP_LABEL_ID,
} from "./config.js";
import { getReposBase } from "./constants.js";
import { parseSimpleYaml } from "./parse-yaml.js";
import { createLogger } from "../logger.js";
import { spawnInTerminal } from "../terminal.js";
import {
  fetchTodoCards,
  fetchNeedsHelpCards,
  fetchReviewCards,
  fetchLatestComment,
  moveCardToList,
  isUserResponse,
} from "./trello-client.js";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const lockFile = resolve(projectRoot, ".poller-running");

/** Derive the .danxbot/config/ path from the REPOS env var. */
function getDanxbotConfigDir(): string {
  const repos = process.env.REPOS || "";
  const name = repos.split(",")[0].split(":")[0].trim();
  if (!name) return "";
  return resolve(getReposBase(), name, ".danxbot/config");
}

const danxbotConfigDir = getDanxbotConfigDir();
const repoConfigYml = danxbotConfigDir
  ? resolve(danxbotConfigDir, "config.yml")
  : "";

const log = createLogger("poller");

let teamRunning = false;
let intervalId: ReturnType<typeof setInterval> | null = null;
let lockCheckId: ReturnType<typeof setInterval> | null = null;

/**
 * Check Needs Help cards for user responses. Cards where a user has replied
 * (latest comment lacks the danxbot marker) are moved to the top of ToDo
 * so they get higher priority than existing ToDo cards.
 */
async function checkNeedsHelp(): Promise<number> {
  let cards;
  try {
    cards = await fetchNeedsHelpCards();
  } catch (error) {
    log.error("Error fetching Needs Help cards", error);
    return 0;
  }

  if (cards.length === 0) return 0;

  let movedCount = 0;
  for (const card of cards) {
    try {
      const latestComment = await fetchLatestComment(card.id);
      if (isUserResponse(latestComment)) {
        log.info(`User responded on "${card.name}" — moving to ToDo`);
        await moveCardToList(card.id, TODO_LIST_ID, "top");
        movedCount++;
      }
    } catch (error) {
      log.error(`Error checking comments for card "${card.name}"`, error);
    }
  }

  return movedCount;
}

let polling = false;

export async function poll(): Promise<void> {
  if (teamRunning || polling) {
    return;
  }

  polling = true;
  try {
    await _poll();
  } finally {
    polling = false;
  }
}

async function _poll(): Promise<void> {
  // Sync danxbot config into target repo on every poll cycle
  syncRepoFiles();

  // Write Trello config into target repo's rules (needs repoRulesDir from sync)
  const repos = process.env.REPOS || "";
  const repoName = repos.split(",")[0].split(":")[0].trim();
  if (repoName) {
    const repoRulesDir = resolve(getReposBase(), repoName, ".claude/rules");
    mkdirSync(repoRulesDir, { recursive: true });
    writeTrelloConfigRule(repoRulesDir);
  }

  log.info("Checking Needs Help + ToDo lists...");

  // Check Needs Help first — user-responded cards get moved to ToDo top
  const movedFromNeedsHelp = await checkNeedsHelp();
  if (movedFromNeedsHelp > 0) {
    log.info(
      `Moved ${movedFromNeedsHelp} card${movedFromNeedsHelp > 1 ? "s" : ""} from Needs Help to ToDo`,
    );
  }

  let cards;
  try {
    cards = await fetchTodoCards();
  } catch (error) {
    log.error("Error fetching cards", error);
    return;
  }

  if (cards.length === 0) {
    log.info("No cards in ToDo — checking if ideator needed");
    await checkAndSpawnIdeator();
    return;
  }

  log.info(
    `Found ${cards.length} card${cards.length > 1 ? "s" : ""} — starting team`,
  );
  cards.forEach((card, i) => log.info(`  ${i + 1}. ${card.name}`));

  spawnClaude("Danxbot Team", "run-team.sh");
}

/** Directory containing files to inject into target repos. */
const injectDir = resolve(dirname(fileURLToPath(import.meta.url)), "inject");

/**
 * Write the Trello config rule file into the target repo so the spawned
 * Claude agent always has the correct IDs — even after context compaction.
 * Generated from env vars, making .env the single source of truth.
 */
function writeTrelloConfigRule(repoRulesDir: string): void {
  const content = `# Trello Config (auto-generated — do not edit)

This file is generated by the danxbot poller from environment variables before each run.

## Board

Board ID: \`${BOARD_ID}\`

## Lists

| List | ID |
|------|----|
| Review | \`${REVIEW_LIST_ID}\` |
| ToDo | \`${TODO_LIST_ID}\` |
| In Progress | \`${IN_PROGRESS_LIST_ID}\` |
| Needs Help | \`${NEEDS_HELP_LIST_ID}\` |
| Done | \`${DONE_LIST_ID}\` |
| Cancelled | \`${CANCELLED_LIST_ID}\` |
| Action Items | \`${ACTION_ITEMS_LIST_ID}\` |

## Labels

| Label | ID |
|-------|----|
| Bug | \`${BUG_LABEL_ID}\` |
| Feature | \`${FEATURE_LABEL_ID}\` |
| Epic | \`${EPIC_LABEL_ID}\` |
| Needs Help | \`${NEEDS_HELP_LABEL_ID}\` |
`;

  writeFileSync(resolve(repoRulesDir, "danx-trello-config.md"), content);
}

/**
 * Validate that .danxbot/config/ in the connected repo and env vars are fully configured.
 * Throws if anything is missing or empty — the poller must not run without valid config.
 */
export function validateRepoConfig(): void {
  const errors: string[] = [];

  // 1. .danxbot/config/ directory must exist in the connected repo
  if (!danxbotConfigDir || !existsSync(danxbotConfigDir)) {
    throw new Error(
      `.danxbot/config/ not found in connected repo. Run ./install.sh to set up danxbot.`,
    );
  }

  // 2. Required files must exist and not be empty
  const requiredFiles = [
    { path: "config.yml", label: "Repo configuration" },
    { path: "overview.md", label: "Repo overview" },
    { path: "workflow.md", label: "Repo workflow" },
    { path: "trello.yml", label: "Trello board/list/label IDs" },
  ];

  for (const { path, label } of requiredFiles) {
    const fullPath = resolve(danxbotConfigDir, path);
    if (!existsSync(fullPath)) {
      errors.push(`Missing .danxbot/config/${path} (${label})`);
    } else {
      const content = readFileSync(fullPath, "utf-8").trim();
      if (!content) {
        errors.push(`Empty .danxbot/config/${path} (${label})`);
      }
    }
  }

  // 3. config.yml must have required fields with non-empty values
  if (repoConfigYml && existsSync(repoConfigYml)) {
    const raw = readFileSync(repoConfigYml, "utf-8");
    const cfg = parseSimpleYaml(raw);

    const requiredFields = [
      { key: "name", label: "Repo name" },
      { key: "url", label: "Repo URL" },
      { key: "runtime", label: "Runtime (docker or local)" },
      { key: "language", label: "Language" },
    ];

    for (const { key, label } of requiredFields) {
      if (!cfg[key] || !cfg[key].trim()) {
        errors.push(
          `Missing '${key}' in .danxbot/config/config.yml (${label})`,
        );
      }
    }

    // If runtime is docker, compose config is required
    if (cfg.runtime === "docker") {
      const dockerFields = [
        { key: "docker.compose_file", label: "Docker compose file" },
        { key: "docker.service_name", label: "Docker service name" },
        { key: "docker.project_name", label: "Docker project name" },
      ];
      for (const { key, label } of dockerFields) {
        if (!cfg[key] || !cfg[key].trim()) {
          errors.push(
            `Missing '${key}' in .danxbot/config/config.yml (${label} — required when runtime is docker)`,
          );
        }
      }

      // Compose file must actually exist
      const composeFile = resolve(danxbotConfigDir, "compose.yml");
      if (!existsSync(composeFile)) {
        errors.push(
          `Missing .danxbot/config/compose.yml (required when runtime is docker)`,
        );
      }
    }
  }

  // 4. Required environment variables (secrets only — IDs come from trello.yml)
  const requiredEnvVars = [
    { name: "ANTHROPIC_API_KEY", label: "Anthropic API key" },
    { name: "GITHUB_TOKEN", label: "GitHub token" },
    { name: "REPOS", label: "Connected repo (name:url)" },
    { name: "TRELLO_API_KEY", label: "Trello API key" },
    { name: "TRELLO_API_TOKEN", label: "Trello API token" },
  ];

  for (const { name, label } of requiredEnvVars) {
    const value = process.env[name];
    if (!value || !value.trim()) {
      errors.push(`Missing env var ${name} (${label})`);
    }
  }

  // 5. Claude auth files must exist
  const claudeAuthDir = resolve(projectRoot, "claude-auth");
  const claudeJson = resolve(claudeAuthDir, ".claude.json");
  if (!existsSync(claudeJson)) {
    errors.push(
      `Missing claude-auth/.claude.json (Claude Code credentials — run ./install.sh Step 6)`,
    );
  }

  if (errors.length > 0) {
    throw new Error(
      `Repo config validation failed:\n  - ${errors.join("\n  - ")}\n\nRun ./install.sh to complete setup.`,
    );
  }

  log.info("Repo config validated successfully");
}

/**
 * Sync danxbot config into the target repo's .claude/ directory. All injected
 * files use the `danx-` prefix so they're clearly identifiable and gitignore-able.
 * Called on every poll cycle to keep targets up to date.
 */
function syncRepoFiles(): void {
  if (!danxbotConfigDir) return;

  const repos = process.env.REPOS || "";
  const repoName = repos.split(",")[0].split(":")[0].trim();
  if (!repoName) return;

  const repoDir = resolve(getReposBase(), repoName);
  const repoClaudeDir = resolve(repoDir, ".claude");
  const repoRulesDir = resolve(repoClaudeDir, "rules");
  const repoSkillsDir = resolve(repoClaudeDir, "skills");
  const repoToolsDir = resolve(repoClaudeDir, "tools");
  const overridesDir = resolve(projectRoot, "repo-overrides");

  mkdirSync(repoRulesDir, { recursive: true });
  mkdirSync(repoToolsDir, { recursive: true });

  // 1. Generate danx-repo-config.md from .danxbot/config/config.yml
  const raw = readFileSync(repoConfigYml, "utf-8");
  const cfg = parseSimpleYaml(raw);

  const name = cfg.name || "unknown";
  const url = cfg.url || "";
  const runtime = cfg.runtime || "local";
  const language = cfg.language || "";
  const framework = cfg.framework || "";
  const testCmd = cfg["commands.test"] || "";
  const lintCmd = cfg["commands.lint"] || "";
  const typeCheckCmd = cfg["commands.type_check"] || "";
  const devCmd = cfg["commands.dev"] || "";
  const composeFile = cfg["docker.compose_file"] || "";
  const serviceName = cfg["docker.service_name"] || "";
  const projectName = cfg["docker.project_name"] || "";
  const sourcePath = cfg["paths.source"] || "";
  const testsPath = cfg["paths.tests"] || "";
  const gitMode = cfg.git_mode || "pr";

  let repoConfigContent = `# Repo Config (auto-generated by danxbot — do not edit)

## Repo

| Field | Value |
|-------|-------|
| Name | \`${name}\` |
| URL | \`${url}\` |
| Runtime | \`${runtime}\` |
| Language | \`${language}\` |
| Framework | \`${framework}\` |
| Git Mode | \`${gitMode}\` |

## Commands

| Command | Value |
|---------|-------|
| Test | \`${testCmd}\` |
| Lint | \`${lintCmd}\` |
| Type Check | \`${typeCheckCmd}\` |
| Dev | \`${devCmd}\` |

## Paths

| Path | Value |
|------|-------|
| Source | \`${sourcePath}\` |
| Tests | \`${testsPath}\` |
`;

  if (runtime === "docker" && composeFile) {
    repoConfigContent += `
## Docker

| Field | Value |
|-------|-------|
| Compose File | \`${composeFile}\` |
| Service Name | \`${serviceName}\` |
| Project Name | \`${projectName}\` |
`;
  }

  writeFileSync(resolve(repoRulesDir, "danx-repo-config.md"), repoConfigContent);

  // 2. Copy overview.md and workflow.md → danx-repo-overview.md / danx-repo-workflow.md
  for (const [src, dest] of [
    ["overview.md", "danx-repo-overview.md"],
    ["workflow.md", "danx-repo-workflow.md"],
  ] as const) {
    const srcPath = resolve(danxbotConfigDir, src);
    if (existsSync(srcPath)) {
      const header = `<!-- AUTO-GENERATED by danxbot from .danxbot/config/${src} — do not edit -->\n\n`;
      const body = readFileSync(srcPath, "utf-8");
      writeFileSync(resolve(repoRulesDir, dest), header + body);
    }
  }

  // 3. Copy repo-specific tools.md → .claude/rules/danx-tools.md
  const toolsDocSource = resolve(danxbotConfigDir, "tools.md");
  if (existsSync(toolsDocSource)) {
    copyFileSync(toolsDocSource, resolve(repoRulesDir, "danx-tools.md"));
  }

  // 4. Copy repo-specific tool scripts → .claude/tools/ (executable)
  const toolsScriptsSource = resolve(danxbotConfigDir, "tools");
  if (existsSync(toolsScriptsSource)) {
    for (const file of readdirSync(toolsScriptsSource)) {
      const src = resolve(toolsScriptsSource, file);
      const dest = resolve(repoToolsDir, file);
      copyFileSync(src, dest);
      try {
        chmodSync(dest, 0o755);
      } catch (e) {
        log.warn(`Failed to chmod ${dest}:`, e);
      }
    }
  }

  // 5. Inject danx-* skills from inject/skills/
  const injectSkillsDir = resolve(injectDir, "skills");
  if (existsSync(injectSkillsDir)) {
    for (const skillName of readdirSync(injectSkillsDir)) {
      const srcSkillDir = resolve(injectSkillsDir, skillName);
      const destSkillDir = resolve(repoSkillsDir, skillName);
      mkdirSync(destSkillDir, { recursive: true });
      for (const file of readdirSync(srcSkillDir)) {
        copyFileSync(resolve(srcSkillDir, file), resolve(destSkillDir, file));
      }
    }
  }

  // 6. Inject danx-* tools from inject/tools/
  const injectToolsDir = resolve(injectDir, "tools");
  if (existsSync(injectToolsDir)) {
    for (const file of readdirSync(injectToolsDir)) {
      const src = resolve(injectToolsDir, file);
      const dest = resolve(repoToolsDir, file);
      copyFileSync(src, dest);
      try {
        chmodSync(dest, 0o755);
      } catch (e) {
        log.warn(`Failed to chmod ${dest}:`, e);
      }
    }
  }

  // 7. Copy compose override to repo-overrides/ (optional)
  const composeSource = resolve(danxbotConfigDir, "compose.yml");
  if (existsSync(composeSource)) {
    mkdirSync(overridesDir, { recursive: true });
    copyFileSync(composeSource, resolve(overridesDir, `${name}-compose.yml`));
  }

  // 8. Copy post-clone hook to repo-overrides/ (optional)
  const hookSource = resolve(danxbotConfigDir, "post-clone.sh");
  if (existsSync(hookSource)) {
    mkdirSync(overridesDir, { recursive: true });
    copyFileSync(hookSource, resolve(overridesDir, `post-clone-${name}.sh`));
  }

  // 9. Copy docs/ → danxbot docs dir (domains and schema)
  const repoDocsDir = resolve(danxbotConfigDir, "docs");
  if (existsSync(repoDocsDir)) {
    const docsDir = resolve(projectRoot, "docs");
    for (const subdir of ["domains", "schema"]) {
      const srcDir = resolve(repoDocsDir, subdir);
      if (!existsSync(srcDir)) continue;
      const destDir = resolve(docsDir, subdir);
      mkdirSync(destDir, { recursive: true });
      for (const file of readdirSync(srcDir)) {
        copyFileSync(resolve(srcDir, file), resolve(destDir, file));
      }
    }
  }

  // 10. Copy .danxbot/features.md → docs/features.md (only if not already present)
  const danxbotDir = resolve(danxbotConfigDir, "..");
  const featuresSource = resolve(danxbotDir, "features.md");
  const featuresDest = resolve(projectRoot, "docs", "features.md");
  if (existsSync(featuresSource) && !existsSync(featuresDest)) {
    mkdirSync(resolve(projectRoot, "docs"), { recursive: true });
    copyFileSync(featuresSource, featuresDest);
  }
}

function spawnClaude(title: string, scriptName: string): void {
  // Safety net: refuse to spawn if lock file already exists (race condition guard)
  if (existsSync(lockFile)) {
    log.error("Lock file exists but teamRunning was false — refusing to spawn");
    return;
  }

  teamRunning = true;

  // Lock file signals that the team is running. The script removes it via EXIT trap.
  writeFileSync(lockFile, String(process.pid));

  const script = resolve(dirname(fileURLToPath(import.meta.url)), scriptName);

  spawnInTerminal({ title, script, cwd: projectRoot });

  // Watch for lock file removal to detect completion.
  startLockWatch();
}

async function checkAndSpawnIdeator(): Promise<void> {
  let reviewCards;
  try {
    reviewCards = await fetchReviewCards();
  } catch (error) {
    log.error("Error fetching Review cards", error);
    return;
  }

  if (reviewCards.length >= REVIEW_MIN_CARDS) {
    log.info(
      `Review has ${reviewCards.length} cards (min ${REVIEW_MIN_CARDS}) — no ideation needed`,
    );
    return;
  }

  log.info(
    `Review has ${reviewCards.length} cards (min ${REVIEW_MIN_CARDS}) — spawning ideator`,
  );
  spawnClaude("Danxbot Ideator", "run-ideator.sh");
}

export function shutdown(): void {
  log.info("Shutting down...");

  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }

  if (lockCheckId) {
    clearInterval(lockCheckId);
    lockCheckId = null;
  }

  // Only remove lock file if no team is running — run-team.sh handles cleanup otherwise
  if (teamRunning) {
    log.info("Team is running — leaving lock file for run-team.sh to clean up");
  } else {
    try {
      if (existsSync(lockFile)) unlinkSync(lockFile);
    } catch (e) {
      log.warn("Failed to remove lock file", e);
    }
  }

  process.exit(0);
}

function startLockWatch(): void {
  lockCheckId = setInterval(() => {
    if (!existsSync(lockFile)) {
      clearInterval(lockCheckId!);
      lockCheckId = null;
      log.info("Team finished — resuming polling");
      teamRunning = false;
      poll().catch((err) =>
        log.error("Re-poll after team completion failed", err),
      );
    }
  }, 5000);
}

export function start(): void {
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  // Validate all config before starting — halt immediately if anything is wrong
  validateRepoConfig();

  const intervalSeconds = config.pollerIntervalMs / 1000;
  log.info(`Started — polling every ${intervalSeconds}s`);

  // Remove stale lock file from a previous run that shut down uncleanly.
  // Only one poller instance runs at a time, so a leftover lock is always stale.
  if (existsSync(lockFile)) {
    log.warn("Stale lock file found — removing");
    unlinkSync(lockFile);
  }

  poll();
  intervalId = setInterval(poll, config.pollerIntervalMs);
}

/** Reset module state for testing. Do not use in production. */
export function _resetForTesting(): void {
  teamRunning = false;
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }
  if (lockCheckId) {
    clearInterval(lockCheckId);
    lockCheckId = null;
  }
}

// Auto-start when run as the direct entrypoint.
// First condition: standard Node.js ESM check.
// Second condition: tsx rewrites import.meta.url, so fall back to argv path match.
const isDirectEntrypoint =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("src/poller/index.ts");

if (isDirectEntrypoint) {
  start();
}
