import { spawn } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync, copyFileSync, unlinkSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  config, TODO_LIST_ID, REVIEW_MIN_CARDS,
  BOARD_ID, REVIEW_LIST_ID, IN_PROGRESS_LIST_ID, NEEDS_HELP_LIST_ID,
  DONE_LIST_ID, CANCELLED_LIST_ID, ACTION_ITEMS_LIST_ID,
  BUG_LABEL_ID, FEATURE_LABEL_ID, EPIC_LABEL_ID, NEEDS_HELP_LABEL_ID,
} from "./config.js";
import { createLogger } from "../logger.js";
import { fetchTodoCards, fetchNeedsHelpCards, fetchReviewCards, fetchLatestComment, moveCardToList, isUserResponse } from "./trello-client.js";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const lockFile = resolve(projectRoot, ".poller-running");
const trelloConfigRule = resolve(projectRoot, ".claude/rules/trello-config.md");
const repoConfigDir = resolve(projectRoot, "repo-config");
const repoConfigYml = resolve(repoConfigDir, "config.yml");

const log = createLogger("poller");

let teamRunning = false;
let intervalId: ReturnType<typeof setInterval> | null = null;
let lockCheckId: ReturnType<typeof setInterval> | null = null;

/**
 * Check Needs Help cards for user responses. Cards where a user has replied
 * (latest comment lacks the danxbot marker) are moved to the top of ToDo
 * so they get higher priority than existing ToDo cards.
 */
async function checkNeedsHelp(): Promise<number> {
  let cards;
  try {
    cards = await fetchNeedsHelpCards();
  } catch (error) {
    log.error("Error fetching Needs Help cards", error);
    return 0;
  }

  if (cards.length === 0) return 0;

  let movedCount = 0;
  for (const card of cards) {
    try {
      const latestComment = await fetchLatestComment(card.id);
      if (isUserResponse(latestComment)) {
        log.info(`User responded on "${card.name}" — moving to ToDo`);
        await moveCardToList(card.id, TODO_LIST_ID, "top");
        movedCount++;
      }
    } catch (error) {
      log.error(`Error checking comments for card "${card.name}"`, error);
    }
  }

  return movedCount;
}

let polling = false;

export async function poll(): Promise<void> {
  if (teamRunning || polling) {
    return;
  }

  polling = true;
  try {
    await _poll();
  } finally {
    polling = false;
  }
}

async function _poll(): Promise<void> {
  // Sync repo config to target locations on every poll cycle
  writeTrelloConfigRule();
  syncRepoFiles();

  log.info("Checking Needs Help + ToDo lists...");

  // Check Needs Help first — user-responded cards get moved to ToDo top
  const movedFromNeedsHelp = await checkNeedsHelp();
  if (movedFromNeedsHelp > 0) {
    log.info(`Moved ${movedFromNeedsHelp} card${movedFromNeedsHelp > 1 ? "s" : ""} from Needs Help to ToDo`);
  }

  let cards;
  try {
    cards = await fetchTodoCards();
  } catch (error) {
    log.error("Error fetching cards", error);
    return;
  }

  if (cards.length === 0) {
    log.info("No cards in ToDo — checking if ideator needed");
    await checkAndSpawnIdeator();
    return;
  }

  log.info(`Found ${cards.length} card${cards.length > 1 ? "s" : ""} — starting team`);
  cards.forEach((card, i) => log.info(`  ${i + 1}. ${card.name}`));

  spawnClaude("Danxbot Team", "run-team.sh");
}

/**
 * Write the Trello config rule file so the spawned Claude agent always has
 * the correct IDs — even after context compaction. This file is generated
 * from env vars, making .env the single source of truth.
 */
function writeTrelloConfigRule(): void {
  const content = `# Trello Config (auto-generated — do not edit)

This file is generated by the poller from environment variables before each run.

## Board

Board ID: \`${BOARD_ID}\`

## Lists

| List | ID |
|------|----|
| Review | \`${REVIEW_LIST_ID}\` |
| ToDo | \`${TODO_LIST_ID}\` |
| In Progress | \`${IN_PROGRESS_LIST_ID}\` |
| Needs Help | \`${NEEDS_HELP_LIST_ID}\` |
| Done | \`${DONE_LIST_ID}\` |
| Cancelled | \`${CANCELLED_LIST_ID}\` |
| Action Items | \`${ACTION_ITEMS_LIST_ID}\` |

## Labels

| Label | ID |
|-------|----|
| Bug | \`${BUG_LABEL_ID}\` |
| Feature | \`${FEATURE_LABEL_ID}\` |
| Epic | \`${EPIC_LABEL_ID}\` |
| Needs Help | \`${NEEDS_HELP_LABEL_ID}\` |
`;

  writeFileSync(trelloConfigRule, content);
}

/**
 * Parse a simple YAML file into a flat key-value structure with dot-notation keys.
 * Handles the repo-config.yml format (scalar values and one level of nesting).
 */
function parseSimpleYaml(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  let currentSection = "";

  for (const rawLine of content.split("\n")) {
    const line = rawLine.trimEnd();
    if (!line || line.startsWith("#")) continue;

    const sectionMatch = line.match(/^(\w[\w_]*):\s*$/);
    if (sectionMatch) {
      currentSection = sectionMatch[1];
      continue;
    }

    const kvMatch = line.match(/^(\s*)(\w[\w_]*):\s*"?([^"]*)"?\s*$/);
    if (kvMatch) {
      const [, indent, key, value] = kvMatch;
      const prefix = indent && indent.length > 0 ? `${currentSection}.` : "";
      if (!indent || indent.length === 0) currentSection = "";
      result[`${prefix}${key}`] = value;
    }
  }

  return result;
}

/**
 * Validate that repo-config/ and env vars are fully configured.
 * Throws if anything is missing or empty — the poller must not run without valid config.
 */
export function validateRepoConfig(): void {
  const errors: string[] = [];

  // 1. repo-config/ directory must exist
  if (!existsSync(repoConfigDir)) {
    throw new Error(
      `repo-config/ directory not found. Run ./install.sh to set up danxbot.`,
    );
  }

  // 2. Required files must exist and not be empty
  const requiredFiles = [
    { path: "config.yml", label: "Repo configuration" },
    { path: "overview.md", label: "Repo overview" },
    { path: "workflow.md", label: "Repo workflow" },
  ];

  for (const { path, label } of requiredFiles) {
    const fullPath = resolve(repoConfigDir, path);
    if (!existsSync(fullPath)) {
      errors.push(`Missing repo-config/${path} (${label})`);
    } else {
      const content = readFileSync(fullPath, "utf-8").trim();
      if (!content) {
        errors.push(`Empty repo-config/${path} (${label})`);
      }
    }
  }

  // 3. config.yml must have required fields with non-empty values
  if (existsSync(repoConfigYml)) {
    const raw = readFileSync(repoConfigYml, "utf-8");
    const cfg = parseSimpleYaml(raw);

    const requiredFields = [
      { key: "name", label: "Repo name" },
      { key: "url", label: "Repo URL" },
      { key: "runtime", label: "Runtime (docker or local)" },
      { key: "language", label: "Language" },
    ];

    for (const { key, label } of requiredFields) {
      if (!cfg[key] || !cfg[key].trim()) {
        errors.push(`Missing '${key}' in repo-config/config.yml (${label})`);
      }
    }

    // If runtime is docker, compose config is required
    if (cfg.runtime === "docker") {
      const dockerFields = [
        { key: "docker.compose_file", label: "Docker compose file" },
        { key: "docker.service_name", label: "Docker service name" },
        { key: "docker.project_name", label: "Docker project name" },
      ];
      for (const { key, label } of dockerFields) {
        if (!cfg[key] || !cfg[key].trim()) {
          errors.push(`Missing '${key}' in repo-config/config.yml (${label} — required when runtime is docker)`);
        }
      }

      // Compose file must actually exist
      const composeFile = resolve(repoConfigDir, "compose.yml");
      if (!existsSync(composeFile)) {
        errors.push(`Missing repo-config/compose.yml (required when runtime is docker)`);
      }
    }
  }

  // 4. Required environment variables
  const requiredEnvVars = [
    { name: "ANTHROPIC_API_KEY", label: "Anthropic API key" },
    { name: "GITHUB_TOKEN", label: "GitHub token" },
    { name: "REPOS", label: "Connected repo (name:url)" },
    { name: "TRELLO_API_KEY", label: "Trello API key" },
    { name: "TRELLO_API_TOKEN", label: "Trello API token" },
    { name: "TRELLO_BOARD_ID", label: "Trello board ID" },
    { name: "TRELLO_REVIEW_LIST_ID", label: "Trello Review list ID" },
    { name: "TRELLO_TODO_LIST_ID", label: "Trello ToDo list ID" },
    { name: "TRELLO_IN_PROGRESS_LIST_ID", label: "Trello In Progress list ID" },
    { name: "TRELLO_NEEDS_HELP_LIST_ID", label: "Trello Needs Help list ID" },
    { name: "TRELLO_DONE_LIST_ID", label: "Trello Done list ID" },
    { name: "TRELLO_CANCELLED_LIST_ID", label: "Trello Cancelled list ID" },
    { name: "TRELLO_ACTION_ITEMS_LIST_ID", label: "Trello Action Items list ID" },
    { name: "TRELLO_BUG_LABEL_ID", label: "Trello Bug label ID" },
    { name: "TRELLO_FEATURE_LABEL_ID", label: "Trello Feature label ID" },
    { name: "TRELLO_EPIC_LABEL_ID", label: "Trello Epic label ID" },
    { name: "TRELLO_NEEDS_HELP_LABEL_ID", label: "Trello Needs Help label ID" },
  ];

  for (const { name, label } of requiredEnvVars) {
    const value = process.env[name];
    if (!value || !value.trim()) {
      errors.push(`Missing env var ${name} (${label})`);
    }
  }

  // 5. Claude auth files must exist
  const claudeAuthDir = resolve(projectRoot, "claude-auth");
  const claudeJson = resolve(claudeAuthDir, ".claude.json");
  if (!existsSync(claudeJson)) {
    errors.push(`Missing claude-auth/.claude.json (Claude Code credentials — run ./install.sh Step 6)`);
  }

  if (errors.length > 0) {
    throw new Error(
      `Repo config validation failed:\n  - ${errors.join("\n  - ")}\n\nRun ./install.sh to complete setup.`,
    );
  }

  log.info("Repo config validated successfully");
}

/**
 * Sync all repo-specific files from repo-config/ to their target locations.
 * Called on every poll cycle to ensure targets are always up to date.
 */
function syncRepoFiles(): void {
  const rulesDir = resolve(projectRoot, ".claude/rules");
  const docsDir = resolve(projectRoot, "docs");
  const overridesDir = resolve(projectRoot, "repo-overrides");

  // 1. Generate repo-config.md from repo-config/config.yml
  const raw = readFileSync(repoConfigYml, "utf-8");
  const cfg = parseSimpleYaml(raw);

  const name = cfg.name || "unknown";
  const url = cfg.url || "";
  const runtime = cfg.runtime || "local";
  const language = cfg.language || "";
  const framework = cfg.framework || "";
  const testCmd = cfg["commands.test"] || "";
  const lintCmd = cfg["commands.lint"] || "";
  const typeCheckCmd = cfg["commands.type_check"] || "";
  const devCmd = cfg["commands.dev"] || "";
  const composeFile = cfg["docker.compose_file"] || "";
  const serviceName = cfg["docker.service_name"] || "";
  const projectName = cfg["docker.project_name"] || "";
  const sourcePath = cfg["paths.source"] || "";
  const testsPath = cfg["paths.tests"] || "";

  let content = `# Repo Config (auto-generated — do not edit)

This file is synced by the poller from \`repo-config/config.yml\` on every poll cycle.

## Repo

| Field | Value |
|-------|-------|
| Name | \`${name}\` |
| URL | \`${url}\` |
| Local Path | \`repos/${name}/\` |
| Runtime | \`${runtime}\` |
| Language | \`${language}\` |
| Framework | \`${framework}\` |

## Commands

| Command | Value |
|---------|-------|
| Test | \`${testCmd}\` |
| Lint | \`${lintCmd}\` |
| Type Check | \`${typeCheckCmd}\` |
| Dev | \`${devCmd}\` |

## Paths

| Path | Value |
|------|-------|
| Source | \`${sourcePath}\` |
| Tests | \`${testsPath}\` |
`;

  if (runtime === "docker" && composeFile) {
    content += `
## Docker

| Field | Value |
|-------|-------|
| Compose File | \`${composeFile}\` |
| Service Name | \`${serviceName}\` |
| Project Name | \`${projectName}\` |
`;
  }

  writeFileSync(resolve(rulesDir, "repo-config.md"), content);

  // 2. Copy overview.md → .claude/rules/repo-overview.md
  copyFileSync(resolve(repoConfigDir, "overview.md"), resolve(rulesDir, "repo-overview.md"));

  // 3. Copy workflow.md → .claude/rules/repo-workflow.md
  copyFileSync(resolve(repoConfigDir, "workflow.md"), resolve(rulesDir, "repo-workflow.md"));

  // 4. Copy compose override to repo-overrides/ (optional)
  const composeSource = resolve(repoConfigDir, "compose.yml");
  if (existsSync(composeSource)) {
    mkdirSync(overridesDir, { recursive: true });
    copyFileSync(composeSource, resolve(overridesDir, `${name}-compose.yml`));
  }

  // 5. Copy post-clone hook to repo-overrides/ (optional)
  const hookSource = resolve(repoConfigDir, "post-clone.sh");
  if (existsSync(hookSource)) {
    mkdirSync(overridesDir, { recursive: true });
    copyFileSync(hookSource, resolve(overridesDir, `post-clone-${name}.sh`));
  }

  // 6. Copy repo.env to repo-overrides/ (optional)
  const envSource = resolve(repoConfigDir, "repo.env");
  if (existsSync(envSource)) {
    mkdirSync(overridesDir, { recursive: true });
    copyFileSync(envSource, resolve(overridesDir, `${name}.env`));
  }

  // 7. Copy docs/ → docs/ (domains and schema)
  const repoDocsDir = resolve(repoConfigDir, "docs");
  if (existsSync(repoDocsDir)) {
    for (const subdir of ["domains", "schema"]) {
      const srcDir = resolve(repoDocsDir, subdir);
      if (!existsSync(srcDir)) continue;
      const destDir = resolve(docsDir, subdir);
      mkdirSync(destDir, { recursive: true });
      for (const file of readdirSync(srcDir)) {
        copyFileSync(resolve(srcDir, file), resolve(destDir, file));
      }
    }
  }

  // 8. Copy features.md → docs/features.md (only if docs/ version doesn't exist yet)
  const featuresSource = resolve(repoConfigDir, "features.md");
  const featuresDest = resolve(docsDir, "features.md");
  if (existsSync(featuresSource) && !existsSync(featuresDest)) {
    mkdirSync(docsDir, { recursive: true });
    copyFileSync(featuresSource, featuresDest);
  }
}

function spawnClaude(title: string, scriptName: string): void {
  // Safety net: refuse to spawn if lock file already exists (race condition guard)
  if (existsSync(lockFile)) {
    log.error("Lock file exists but teamRunning was false — refusing to spawn");
    return;
  }

  teamRunning = true;
  log.info(`Spawning Claude in new terminal tab (${title})...`);

  const env = { ...process.env };
  for (const key of Object.keys(env)) {
    if (key.startsWith("CLAUDECODE")) {
      delete env[key];
    }
  }

  // Lock file signals that the team is running. The script removes it via EXIT trap.
  writeFileSync(lockFile, String(process.pid));

  const script = resolve(dirname(fileURLToPath(import.meta.url)), scriptName);

  // wt.exe returns immediately — the Claude process runs in the new tab.
  spawn("wt.exe", ["-w", "0", "new-tab", "--title", title, "wsl.exe", "-e", "bash", script], {
    cwd: projectRoot,
    stdio: "ignore",
    env,
    detached: true,
  }).unref();

  // Watch for lock file removal to detect completion.
  startLockWatch();
}

async function checkAndSpawnIdeator(): Promise<void> {
  let reviewCards;
  try {
    reviewCards = await fetchReviewCards();
  } catch (error) {
    log.error("Error fetching Review cards", error);
    return;
  }

  if (reviewCards.length >= REVIEW_MIN_CARDS) {
    log.info(`Review has ${reviewCards.length} cards (min ${REVIEW_MIN_CARDS}) — no ideation needed`);
    return;
  }

  log.info(`Review has ${reviewCards.length} cards (min ${REVIEW_MIN_CARDS}) — spawning ideator`);
  spawnClaude("Danxbot Ideator", "run-ideator.sh");
}

export function shutdown(): void {
  log.info("Shutting down...");

  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }

  if (lockCheckId) {
    clearInterval(lockCheckId);
    lockCheckId = null;
  }

  // Only remove lock file if no team is running — run-team.sh handles cleanup otherwise
  if (teamRunning) {
    log.info("Team is running — leaving lock file for run-team.sh to clean up");
  } else {
    try {
      if (existsSync(lockFile)) unlinkSync(lockFile);
    } catch (e) { log.warn("Failed to remove lock file", e); }
  }

  process.exit(0);
}

function startLockWatch(): void {
  lockCheckId = setInterval(() => {
    if (!existsSync(lockFile)) {
      clearInterval(lockCheckId!);
      lockCheckId = null;
      log.info("Team finished — resuming polling");
      teamRunning = false;
      poll().catch((err) => log.error("Re-poll after team completion failed", err));
    }
  }, 5000);
}

export function start(): void {
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);

  // Validate all config before starting — halt immediately if anything is wrong
  validateRepoConfig();

  const intervalSeconds = config.pollerIntervalMs / 1000;
  log.info(`Started — polling every ${intervalSeconds}s`);

  // Remove stale lock file from a previous run that shut down uncleanly.
  // Only one poller instance runs at a time, so a leftover lock is always stale.
  if (existsSync(lockFile)) {
    log.warn("Stale lock file found — removing");
    unlinkSync(lockFile);
  }

  poll();
  intervalId = setInterval(poll, config.pollerIntervalMs);
}

/** Reset module state for testing. Do not use in production. */
export function _resetForTesting(): void {
  teamRunning = false;
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }
  if (lockCheckId) {
    clearInterval(lockCheckId);
    lockCheckId = null;
  }
}

// Auto-start when run as the direct entrypoint.
// First condition: standard Node.js ESM check.
// Second condition: tsx rewrites import.meta.url, so fall back to argv path match.
const isDirectEntrypoint =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("src/poller/index.ts");

if (isDirectEntrypoint) {
  start();
}
