/**
 * Renders `danx-repo-config.md` from the parsed `config.yml` map.
 *
 * Lives in its own module (per `.claude/rules/danx-repo-workflow.md`) so it
 * can be unit-tested without pulling the env-var-heavy config chain that
 * `src/poller/index.ts` requires at import time.
 *
 * Required-field reads throw on missing/empty values rather than masking
 * config bugs with silent `|| "unknown"` fallbacks ("Fallbacks Are Bugs —
 * Fail Loud, Never Fail Silent" per `.claude/rules/code-quality.md`). The
 * authoritative validator is `validateRepoConfig` in `src/poller/index.ts`,
 * which boot-time-checks the same fields; the throws here protect against
 * any future code path that bypasses boot validation (e.g., a runtime
 * settings flip that re-enables Trello with a half-edited config.yml).
 */
export function renderRepoConfigMarkdown(cfg: Record<string, string>): string {
  const requireField = (key: string): string => {
    const value = cfg[key];
    if (!value || !value.trim()) {
      throw new Error(
        `renderRepoConfigMarkdown: required field '${key}' is missing or empty in config.yml. Run validateRepoConfig before syncing rule files, or check that .danxbot/config/config.yml is complete.`,
      );
    }
    return value;
  };
  const optionalField = (key: string, fallback = ""): string =>
    cfg[key] || fallback;

  const name = requireField("name");
  const url = requireField("url");
  const runtime = requireField("runtime");
  const language = requireField("language");
  const framework = optionalField("framework");
  const gitMode = optionalField("git_mode", "pr");
  const composeFile = optionalField("docker.compose_file");

  let out = `# Repo Config (auto-generated by danxbot — do not edit)

## Repo

| Field | Value |
|-------|-------|
| Name | \`${name}\` |
| URL | \`${url}\` |
| Runtime | \`${runtime}\` |
| Language | \`${language}\` |
| Framework | \`${framework}\` |
| Git Mode | \`${gitMode}\` |

## Commands

| Command | Value |
|---------|-------|
| Test | \`${optionalField("commands.test")}\` |
| Lint | \`${optionalField("commands.lint")}\` |
| Type Check | \`${optionalField("commands.type_check")}\` |
| Dev | \`${optionalField("commands.dev")}\` |

## Paths

| Path | Value |
|------|-------|
| Source | \`${optionalField("paths.source")}\` |
| Tests | \`${optionalField("paths.tests")}\` |
`;

  if (runtime === "docker" && composeFile) {
    out += `
## Docker

| Field | Value |
|-------|-------|
| Compose File | \`${composeFile}\` |
| Service Name | \`${requireField("docker.service_name")}\` |
| Project Name | \`${requireField("docker.project_name")}\` |
`;
  }
  return out;
}
