import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { TrelloConfig } from "../types.js";

/**
 * Generate danx-trello-config.md, the auto-synced rule file that exposes
 * Trello board/list/label IDs to the dispatched agent. Pure I/O — the only
 * side effect is writing the file at `<repoRulesDir>/danx-trello-config.md`.
 *
 * The Triaged label is optional: it's rendered when `triagedLabelId` is set
 * and omitted otherwise, so boards set up before the triage skill landed
 * don't carry a dangling "Triaged | undefined" row.
 */
export function writeTrelloConfigRule(
  trello: TrelloConfig,
  repoRulesDir: string,
): void {
  const labelRows = [
    `| Bug | \`${trello.bugLabelId}\` |`,
    `| Feature | \`${trello.featureLabelId}\` |`,
    `| Epic | \`${trello.epicLabelId}\` |`,
    `| Needs Help | \`${trello.needsHelpLabelId}\` |`,
  ];
  if (trello.triagedLabelId) {
    labelRows.push(`| Triaged | \`${trello.triagedLabelId}\` |`);
  }

  const content = `# Trello Config (auto-generated — do not edit)

This file is generated by the danxbot poller from environment variables before each run.

## Board

Board ID: \`${trello.boardId}\`

## Lists

| List | ID |
|------|----|
| Review | \`${trello.reviewListId}\` |
| ToDo | \`${trello.todoListId}\` |
| In Progress | \`${trello.inProgressListId}\` |
| Needs Help | \`${trello.needsHelpListId}\` |
| Done | \`${trello.doneListId}\` |
| Cancelled | \`${trello.cancelledListId}\` |
| Action Items | \`${trello.actionItemsListId}\` |

## Labels

| Label | ID |
|-------|----|
${labelRows.join("\n")}
`;

  writeFileSync(resolve(repoRulesDir, "danx-trello-config.md"), content);
}
